---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/15 下午11:59
---
---@class BufferBase
local BufferBase = class("BufferBase")

--- 初始化
function BufferBase:ctor()
    ---@type boolean 这个buff 会对 玩家起作用？
    self._isNotPlayer = false
    ---@type boolean 这个buff 对怪物起作用
    self._isHave = false
    
end

return BufferBase