--- game player 里面相关
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/12 上午12:06
---
---@class GameMainConfig
local GameBufferConfig = {
}

--- 玩家可以 附加给 怪物的 相关buff
GameMainConfig.Player = {
    frostBuffer = 1
}

return GameMainConfig