---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/19 18:44
---
print("加载 ProtocolManager.lua 文件")

print("require service files lua script start")

---------------------------- error 101     ----------------------------
Error = require("application.app.net.webSocket.luaProtocol.common.error")
-----------------------------------------------------------------------

----------------------------  pong 104    ----------------------------
Pong = require("application.app.net.webSocket.luaProtocol.common.pong")
-----------------------------------------------------------------------
----------------------------  login   ----------------------------
LoginRequest = require("application.app.net.webSocket.luaProtocol.login.loginRequest")
LoginResponse = require("application.app.net.webSocket.luaProtocol.login.loginResponse")
LoginUserServerInfoData = require("application.app.net.webSocket.luaProtocol.login.loginUserServerInfoData")

-----------------------------------------------------------------------------------

----------------------------------reigister-------------------------------------------------
RegisterRequest = require("application.app.net.webSocket.luaProtocol.register.registerRequest")
RegisterResponse = require("application.app.net.webSocket.luaProtocol.register.registerResponse")
-----------------------------------------------------------------------------------------------------------

----------------------------------loginTapToStart-------------------------------------------------
LoginTapToStartRequest = require("application.app.net.webSocket.luaProtocol.login.loginTapToStartRequest")
LoginTapToStartResponse = require("application.app.net.webSocket.luaProtocol.login.loginTapToStartResponse")
-----------------------------------------------------------------------------------------------------------

----------------------------------serverConfig-------------------------------------------------
ServerConfigRequest = require("application.app.net.webSocket.luaProtocol.serverConfig.serverConfigRequest")
ServerConfigResponse = require("application.app.net.webSocket.luaProtocol.serverConfig.serverConfigResponse")
-----------------------------------------------------------------------------------------------------------

----------------------------------bag-------------------------------------------------
ItemBaseData = require("application.app.net.webSocket.luaProtocol.bag.itemBaseData")
AllBagItemRequest = require("application.app.net.webSocket.luaProtocol.bag.allBagItemRequest")
AllBagItemResponse = require("application.app.net.webSocket.luaProtocol.bag.allBagItemResponse")
BagUserItemMsgData = require("application.app.net.webSocket.luaProtocol.bag.bagUserItemMsgData")
-----------------------------------------------------------------------------------------------------------

----------------------------------equipment-------------------------------------------------
EquipmentAllDataRequest = require("application.app.net.webSocket.luaProtocol.equipment.equipmentAllDataRequest")
EquipmentAllDataResponse = require("application.app.net.webSocket.luaProtocol.equipment.equipmentAllDataResponse")
EquipmentData = require("application.app.net.webSocket.luaProtocol.equipment.equipmentData")
EquipmentGlossaryData = require("application.app.net.webSocket.luaProtocol.equipment.equipmentGlossaryData")


EquipmentBaseData = require("application.app.net.webSocket.luaProtocol.equipment.Base.equipmentBaseData")
EquipmentConfigBaseData = require("application.app.net.webSocket.luaProtocol.equipment.Base.equipmentConfigBaseData")
EquipmentDesBaseData = require("application.app.net.webSocket.luaProtocol.equipment.Base.equipmentDesBaseData")
EquipmentGrowthConfigBaseData = require(
        "application.app.net.webSocket.luaProtocol.equipment.Base.equipmentGrowthConfigBaseData")
EquipmentGrowthViceConfigBaseData = require(
        "application.app.net.webSocket.luaProtocol.equipment.Base.equipmentGrowthViceConfigBaseData")
EquipmentPrimaryConfigBaseData = require(
        "application.app.net.webSocket.luaProtocol.equipment.Base.equipmentPrimaryConfigBaseData")

-----------------------------------------------------------------------------------------------------------

--------------------------------------------Weapon------------------------------------------------------------
WeaponPlayerUserDataRequest = require("application.app.net.webSocket.luaProtocol.weapon.weaponPlayerUserDataRequest")
WeaponPlayerUserDataResponse = require("application.app.net.webSocket.luaProtocol.weapon.weaponPlayerUserDataResponse")

WeaponPlayerBagDataRequest = require("application.app.net.webSocket.luaProtocol.weapon.weaponPlayerBagDataRequest")
WeaponPlayerBagDataResponse = require("application.app.net.webSocket.luaProtocol.weapon.weaponPlayerBagDataResponse")

WeaponPlayerUserDataStruct = require("application.app.net.webSocket.luaProtocol.weapon.weaponPlayerUserDataStruct")
WeaponsConfigData = require("application.app.net.webSocket.luaProtocol.weapon.weaponsConfigData")
--------------------------------------------end Weapon------------------------------------------------------------

--------------------------------------------playerUser-----------------------------------------------------------

PlayerSceneInfoData = require("application.app.net.webSocket.luaProtocol.playerUser.playerSceneInfoData")
UserMsgInfoData = require("application.app.net.webSocket.luaProtocol.playerUser.userMsgInfoData")

------------------------------------------end playerUser----------------------------------------------------------

--------------------------------------------PhysicalPower-----------------------------------------------------------

PhysicalPowerRequest = require("application.app.net.webSocket.luaProtocol.physicalPower.physicalPowerRequest")
PhysicalPowerResponse = require("application.app.net.webSocket.luaProtocol.physicalPower.physicalPowerResponse")
PhysicalPowerSecondsResponse = require("application.app.net.webSocket.luaProtocol.physicalPower.physicalPowerSecondsResponse")

PhysicalPowerInfoData = require("application.app.net.webSocket.luaProtocol.physicalPower.physicalPowerInfoData")

--------------------------------------------end PhysicalPower-------------------------------------------------------

------------------------------------------gameMain--------------------------------------------------------------------

GameMainUIPanelRequest = require("application.app.net.webSocket.luaProtocol.gameMain.gameMainUIPanelRequest")
GameMainUserResourcesResponse = require "application.app.net.webSocket.luaProtocol.gameMain.gameMainUserResourcesResponse"
OpenGameMainUIPanelRequest=require("application.app.net.webSocket.luaProtocol.gameMain.openGameMainUIPanelRequest")
GetGameMainCharacterAllRequest=require("application.app.net.webSocket.luaProtocol.gameMain.getGameMainCharacterAllRequest")
GetGameMainCharacterAllResponse=require("application.app.net.webSocket.luaProtocol.gameMain.getGameMainCharacterAllResponse")

------------------------------------------end gameMain--------------------------------------------------------------------

------------------------------------------  character  --------------------------------------------------------------------

AcquireCharacterRequest = require("application.app.net.webSocket.luaProtocol.character.acquireCharacterRequest")
AcquireCharacterResponse = require("application.app.net.webSocket.luaProtocol.character.acquireCharacterResponse")
CharacterBaseData = require("application.app.net.webSocket.luaProtocol.character.characterBaseData")
CharacterEquipmentIDData = require("application.app.net.webSocket.luaProtocol.character.characterEquipmentIDData")
CharacterWeaponIDData = require("application.app.net.webSocket.luaProtocol.character.characterWeaponIDData")
CreateCharacterRequest = require("application.app.net.webSocket.luaProtocol.character.createCharacterRequest")
CreateCharacterResponse = require("application.app.net.webSocket.luaProtocol.character.createCharacterResponse")
GameMainTeamCharacterIDData = require("application.app.net.webSocket.luaProtocol.character.gameMainTeamCharacterIDData")
CharacterConfigData = require("application.app.net.webSocket.luaProtocol.character.characterConfigData")
CharacterConfigResponse = require("application.app.net.webSocket.luaProtocol.character.characterConfigResponse")

------------------------------------------end character--------------------------------------------------------------------

------------------------------------------  user  --------------------------------------------------------------------
GameMainUserInfoToRequest = require("application.app.net.webSocket.luaProtocol.user.gameMainUserInfoToRequest")
GameMainUserInfoToResponse = require("application.app.net.webSocket.luaProtocol.user.gameMainUserInfoToResponse")
------------------------------------------end user--------------------------------------------------------------------

------------------------------------------  resource  --------------------------------------------------------------------
GameMainUserResourcesResponse = require("application.app.net.webSocket.luaProtocol.resources.gameMainUserResourcesResponse")
------------------------------------------end user--------------------------------------------------------------------
-- local protocols = {}

local ProtocolManager = {}


-- table扩展方法，map的大小
function table.mapSize(map)
    local size = 0
    for _, _ in pairs(map) do
        size = size + 1
    end
    return size
end

function ProtocolManager.initProtocolManager()

end

return ProtocolManager
