---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zjy.
--- DateTime: 2023/11/27 15:15
---
local DialogConfig = {
    ButtonType = {
        YesNO = 1,
        Yes = 2
    },
    Result = {
        OK = 1,
        Yes = 2,
        No = 3
    },
    config={
        backgroundCloseButton="Button",
        titleText="Text",
        BodyText="Tips",
        NoButton="GridButton/NoBtn",
        NoButtonText="GridButton/NoBtn/Text",
        YesButton="GridButton/YesBtn",
        YesButtonText="GridButton/YesBtn/Text",
    }

}

return DialogConfig
