---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/11/27 15:15
---
local DialogConfig = {
    ButtonType = {
        YesNO = 1,
        Yes = 2
    },
    Result = {
        OK = 1,
        Yes = 2,
        No = 3
    }

}

return DialogConfig
