--- 通知界面的 控制器
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/11/27 15:08
---
---@class UICommonViewController
UICommonViewController = class("UICommonViewController")


function UICommonViewController:OnInit()

end
