--- 通知界面
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/11/27 14:54
---

---@class UICommonView:LuaUIObject
UICommonView = class("UICommonView", LuaUIObject);
function UICommonView:OnInit(gameObject)
    self.config = require("Game.UI.CommonUI.DialogConfig")
    local backgroundCloseTransform = gameObject.transform:Find(self.config.config.backgroundCloseButton)
    local titleTextTransform = gameObject.transform:Find(self.config.config.titleText)
    local BodyTextTransform = gameObject.transform:Find(self.config.config.BodyText)
    local NoButtonTransform = gameObject.transform:Find(self.config.config.NoButton)
    local NoButtonTextTransform = gameObject.transform:Find(self.config.config.NoButtonText)
    local YesButtonTransform = gameObject.transform:Find(self.config.config.YesButton)
    local YesButtonTextTransform = gameObject.transform:Find(self.config.config.YesButtonText)

    self.backgroundCloseButton = backgroundCloseTransform:GetComponent("Button")
    self.titleText = titleTextTransform:GetComponent("Text")
    self.BodyText = BodyTextTransform:GetComponent("Text")
    self.NoButton = NoButtonTransform:GetComponent("Button")
    self.NoButtonText = NoButtonTextTransform:GetComponent("Text")
    self.YesButton = YesButtonTransform:GetComponent("Button")
    self.YesButtonText = YesButtonTextTransform:GetComponent("Text")
    self.objCanvasGroup = gameObject:GetComponent("CanvasGroup")
end

function UICommonView:OnShow()
    self.objCanvasGroup.alpha = 1
    self.objCanvasGroup.interactable = true
    self.objCanvasGroup.blocksRaycasts = true
end

function UICommonView:OnClose()
    self.objCanvasGroup.alpha = 0
    self.objCanvasGroup.interactable = false
    self.objCanvasGroup.blocksRaycasts = false
end

---@param active boolean
function UICommonView:Active(active)
    if active then
        self:OnShow()
    else
        self:OnClose()
    end
end

function UICommonView:SetTitleText(text)
    self.titleText.text = text
end

function UICommonView:SetBodyText(text)
    self.BodyText.text = text
end

function UICommonView:SetupButtons(type)
    local buttonFunction = {
        [self.config.ButtonType.YesNO] = function()
            self.NoButton.gameObject:SetActive(true)
            self.YesButton.gameObject:SetActive(true)
        end,
        [self.config.ButtonType.Yes] = function()
            self.NoButton.gameObject:SetActive(false)
            self.YesButton.gameObject:SetActive(true)
        end,
    }
    local switchAction = buttonFunction[type]
    switchAction()
end

function UICommonView:OnOpen(type, title, body, yesButtonText, noButtonText, onClick)
    self:Active(true)
    self:SetTitleText(title)
    self:SetupButtons(type)
    self:SetBodyText(body)
    if self.backgroundCloseButton ~= nil then
        self:SetListener(self.backgroundCloseButton, function()
            self:OnClose()
        end)
    end
    self.YesButtonText.text = yesButtonText
    self.NoButtonText.text = noButtonText
    self:SetListener(self.YesButton, function()
        self:OnClose()
        onClick(self.config.Result.Yes)
    end)
    self:SetListener(self.NoButton, function()
        self:OnClose()
        onClick(self.config.Result.No)
    end)
end
