---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/6 23:24
---

ServerDataManager = {}
local bagItemEntityList

function ServerDataManager:GetInstance()
    return ServerDataManager
end

function ServerDataManager:SetItemBaseDataList(list)
    bagItemEntityList = list
end

return ServerDataManager

