---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/6 23:24
---

ServerDataManager = {}

function ServerDataManager:GetInstance()
    return ServerDataManager
end 