---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/22 14:40
---
---@class LoginResponse
local LoginResponse = class("LoginResponse")
local this = LoginResponse
function LoginResponse:ctor()
    ---@type string
    self.token = ""                    ---java.lang.String
    ---@type number
    self.uid = 0                       -- long
    ---@type LoginUserServerInfoData
    self.loginUserServerInfoData = nil -- LoginUserServerInfoData
end

function LoginResponse:new(token, uid, loginUserServerInfoData)
    --local obj = LoginResponse.New()
    -- local obj = {
    self.token = token                                     ---java.lang.String
    self.uid = uid                                         -- long
    self.loginUserServerInfoData = loginUserServerInfoData -- LoginUserServerInfoData
    -- }
    -- setmetatable(obj, self)
    -- self.__index = self
    return self
end

function LoginResponse:protocolId()
    return 1001
end

function LoginResponse:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function LoginResponse:read(data)
    -- local jsonString = buffer:readString()
    -- ---字节读取器中存放字符
    -- local data = JSON.decode(jsonString)
    local pakcet = LoginUserServerInfoData();
    local packetData = pakcet:read(data);
    local jsonData = LoginResponse:new(
        data.token,
        data.uid, packetData)
    return jsonData
end

return LoginResponse
