--- GameMainViewController gameMain 界面 UI控制器 向外发送
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/15 23:41

---@class GameMainViewController
---@author zjy
GameMainViewController = {}
local modelView
function GameMainViewController:GetInstance()
    return GameMainViewController
end

function GameMainViewController:OnInit(_modelView)
    modelView = _modelView
end
function GameMainViewController.OnOpen()
end
