---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/17 15:53
---

UIModelInterfaces = {}

UIEventNotificationDict = {}

UIComponentManager = {}

function UIComponentManager:InitUIModelComponent()
    UIModelInterfaces["loginUI"] = LoginUIModelView
    UIModelInterfaces["gameMainUI"] = GameMainUIModelView
    ---循环遍历
    for i, v in pairs(UIModelInterfaces) do
        for _i, _v in ipairs(v:Notification()) do
            local uiAction = UIEventNotificationDict[_v]
            if uiAction == nil then
                local data = v
                --- 当前 UI事件没有存储
                UIEventNotificationDict[_v] = function(_eventNotification)
                    data:NotificationHandler(_eventNotification)
                end
            else
                error("[class:" .. i .. "]" .. "[Notification:" .. _v .. "] 有重复的事件id")
            end
        end
    end

end

function UIComponentManager.DispatchEvent(name, body)
    local eventUI = require("Game.Common.UINotification").New()
    eventUI:SetNotification(name, body)
    local eventAction = UIEventNotificationDict[name]
    if eventAction ~= nil then
        eventAction(eventUI)
    end
end

return UIComponentManager