---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/16 0:10
---

local GameMainVIew = BaseClass(UIBaseView).New()

function GameMainVIew:OnInit()
    print("GameMain:OnInit")
    --- GameMain ViewPanel
    local ViewPanel = GameMainVIew:GetViewPanel()
    --- 转换水晶 按钮
    self.GemsTimeButton = ViewPanel.GemsTim_UISerializableKeyObject:GetObjType("click") or CS.UnityEngine.UI.Button
    self.GemsText = ViewPanel.GemsTim_UISerializableKeyObject:GetObjType("numText") or CS.UnityEngine.UI.Text
    local data = CS.SpringContext.GetBean("PlayerUserCaCheData") or CS.ZJYFrameWork.Hotfix.Common.PlayerUserCaCheData
    --- 显示名字
    ViewPanel.top_head_Name_Text.text = data.userName
    --- 付费水晶 商店充值跳转按钮
    self.GemButton = ViewPanel.Gem_UISerializableKeyObject:GetObjType("click") or CS.UnityEngine.UI.Button
    --- 显示付费水晶
    self.GemText = ViewPanel.Gem_UISerializableKeyObject:GetObjType("numText") or CS.UnityEngine.UI.Text
    --- 显示金币
    self.GoldCoinText = ViewPanel.Gem_UISerializableKeyObject:GetObjType("numText") or CS.UnityEngine.UI.Text
    --- 购买金币，第一跳转商场兑换
    self.GoldTimButton = ViewPanel.glod_UISerializableKeyObject:GetObjType("click") or CS.UnityEngine.UI.Button
    CS.Util.SetListener(ViewPanel.headImgClick, (function()
        --- 点击头像
        CS.Debug.Log("点击头像，进行更换")
        --- 目前来说还不知道需不需要
    end))
    CS.Util.SetListener(self.GoldTimButton, function()
        --- 购买金币 这个是需要 去兑换
        --- 先写 但是不知道需要不要 明确
    end)

end

function GameMainVIew:OnShow()
    CS.Debug.Log("GameMain:OnShow")
    GameMainVIew.super:OnShow()
end

---@param dateTime
function GameMainVIew:ShowNowTime(dateTime)
    local timeNum = string.format("%.0f", (dateTime.time / 1000));
    local time = os.date("%Y年%m月%d日 %H时%M分%S秒", tonumber(timeNum))
    local ViewPanel = GameMainVIew:GetViewPanel()
    ViewPanel.TimeShow_Text.text = time
end
return GameMainVIew