---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/27 13:37
---

local apiRequest = class("apiRequest")
apiRequest.Uri = nil
apiRequest.Method = nil
apiRequest._watch = CS.System.Diagnostics.Stopwatch

local _bhRequest = nil
local _onBeforeSend = nil
local _onSuccess = nil
local _onError = nil
local _onComplete = nil

function apiRequest.Init(method, uri, data, onBeforeSend, onSuccess, onError, onComplete)
    apiRequest.Uri = uri
    apiRequest.Method = method
    _bhRequest = CS.BestHTTP.HttpRequest(apiRequest.Uri, apiRequest.Method)
    _bhRequest:SetHeader("Accept-Encoding", "gzip")
    _bhRequest:SetHeader("App-Version", UserAgent:Version())
    _bhRequest:SetHeader("User-Agent", UserAgent:Value())
    _bhRequest:SetHeader("Content-Type", "application/json")
    _bhRequest.RawData = data
    _onBeforeSend = onBeforeSend
    _onSuccess = onSuccess
    _onError = onError
    _onComplete = onComplete
end

function apiRequest.HandleResponse(originalBhRequest, bhResponse)
    apiRequest._watch.Stop()
    local elapsedMsec = apiRequest._watch.ElapsedMilliseconds
    local apiResponse = require("application.app.net.http.apiResponse")()
    apiResponse.new(apiRequest, bhResponse, elapsedMsec)

    if apiResponse.IsSuccess() then
        if _onSuccess ~= nil then
            _onSuccess(apiResponse)
        end
    else
        if _onError ~= nil then
            _onError(apiResponse)
        end
    end
    if _onComplete ~= nil then
        _onComplete(apiResponse)
    end
end

function apiRequest.Send()
    if _onBeforeSend ~= nil then
        _onBeforeSend(apiRequest)
    end
    apiRequest._watch = CS.System.Diagnostics.Stopwatch()
    apiRequest._watch.Start()
    if _bhRequest == nil then
        if Debug > 0 then
            PrintDebug("not c# set HttpRequest data")
        end
        return
    end
    _bhRequest.Send()
end

return apiRequest
