--- ping response
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/24 10:35
---
---@class Pong pong
local Pong = {}
function Pong:new(time)
    local obj = {
        time = time, -- long
    }
    setmetatable(obj, self)
    self.__index = self
    return obj
end

function Pong:protocolId()
    return 104
end

function Pong:write(buffer, packet)
    --printError(type(packet))
    if packet == nil then
        --log.log(type(packet))
        return
    end
    local data = packet or Pong
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function Pong:read(buffer)
    local jsonString = buffer:readString()
    ---字节读取器中存放字符
    local data = JSON.decode(jsonString)
    return Pong:new(data.packet.time)
end

return Pong