--- 角色 每个 配置 data
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/5/19 下午3:40
---@class CharacterConfigData
local CharacterConfigData = class("CharacterConfigData")
function CharacterConfigData:ctor()
    --- 下标
    ---@type number
    self.CId = 0; ---java.lang.integer
    --- 品质
    ---@type number 品质
    self.quality = 0;
    --- 角色id
    ---@type number
    self.characterId = 0;
    --- 角色名
    ---@type string
    self.characterName = string.empty;
    --- 角色资源名
    ---@type string
    self.characterRes = string.empty;
    --- 1级的攻击属性
    ---@type number
    self.Level1Atk = 0;
    --- 1级的暴击率
    ---@type number
    self.Level1CriticalHitChance = 0;
    --- 1级的生命值
    ---@type number
    self.Level1HpValue = 0;
    --- 1级防御力
    ---@type number
    self.Level1Def = 0;
    --- 1级元素精通
    ---@type number
    self.Level1ElementMastery = 0;
    --- 1级元素充能效率
    ---@type number
    self.Level1ChargingEfficiencyOfElements = 0;
    --- 1级暴击伤害
    ---@type number
    self.Level1CriticalHitDamage = 0;
    --- 当前等级没有装备武器攻击属性
    ---@type number
    self.Level1NoWAtk = 0;
    --- 角色默认武器id
    ---@type number
    self.characterDefaultWeaponId = 0;
    --- 角色默认武器是什么类型
    ---@type number
    self.weaponType = 0;
    --- 当前强化的星阶 最大
    ---@type number
    self.maxReinforcementEqualOrder = 0;
    --- 角色创建出来的初始等级
    ---@type number
    self.lvInit = 0;
    --- 角色创建出来初始最大等级
    ---@type number
    self.initLvMax = 0;
    --- 角色元素伤害类型
    ---@type number
    self.elementType = 0;
    --- 缩小头像
    ---@type string
    self.bagSideIcon = string.empty;
    --- 头像
    ---@type string
    self.bagClickIcon = string.empty;
end
--- 协议id
---@return number
function CharacterConfigData:protocolId()
    return 224
end
--- 赋值
--- @param CId any
--- @param quality any
--- @param characterId any
--- @param characterName any
--- @param characterRes any
--- @param level1Atk any
--- @param level1CriticalHitChance any
--- @param level1HpValue any
--- @param level1Def any
--- @param level1ElementMastery any
--- @param level1ChargingEfficiencyOfElements any
--- @param level1CriticalHitDamage any
--- @param level1NoWAtk any
--- @param characterDefaultWeaponId any
--- @param weaponType any
--- @param maxReinforcementEqualOrder any
--- @param lvInit any
--- @param initLvMax any
--- @param elementType any
--- @param bagSideIcon any
--- @param bagClickIcon any
--- @return CharacterConfigData
function CharacterConfigData:new(CId, quality, characterId, characterName, characterRes, level1Atk,
                                 level1CriticalHitChance, level1HpValue, level1Def, level1ElementMastery,
                                 level1ChargingEfficiencyOfElements, level1CriticalHitDamage,
                                 level1NoWAtk, characterDefaultWeaponId, weaponType,
                                 maxReinforcementEqualOrder, lvInit, initLvMax, elementType, bagSideIcon, bagClickIcon)
    self.CId = CId;
    self.quality = quality;
    self.characterId = characterId;
    self.characterName = characterName;
    self.characterRes = characterRes;
    self.Level1Atk = level1Atk;
    self.Level1CriticalHitChance = level1CriticalHitChance;
    self.Level1HpValue = level1HpValue;
    self.Level1Def = level1Def;
    self.Level1ElementMastery = level1ElementMastery;
    self.Level1ChargingEfficiencyOfElements = level1ChargingEfficiencyOfElements;
    self.Level1CriticalHitDamage = level1CriticalHitDamage;
    self.Level1NoWAtk = level1NoWAtk;
    self.characterDefaultWeaponId = characterDefaultWeaponId;
    self.weaponType = weaponType;
    self.maxReinforcementEqualOrder = maxReinforcementEqualOrder;
    self.lvInit = lvInit;
    self.initLvMax = initLvMax;
    self.elementType = elementType;
    self.bagSideIcon = bagSideIcon;
    self.bagClickIcon = bagClickIcon;
    return self
end
--- 读取值
---@param data CharacterConfigData
function CharacterConfigData:read(data)
    return self:new(
            data.CId,
            data.quality,
            data.characterId,
            data.characterName,
            data.characterRes,
            data.Level1Atk,
            data.Level1CriticalHitChance,
            data.Level1HpValue,
            data.Level1Def,
            data.Level1ElementMastery,
            data.Level1ChargingEfficiencyOfElements,
            data.Level1CriticalHitDamage,
            data.Level1NoWAtk,
            data.characterDefaultWeaponId,
            data.weaponType,
            data.maxReinforcementEqualOrder,
            data.lvInit,
            data.initLvMax,
            data.elementType,
            data.bagSideIcon,
            data.bagClickIcon
    )

end
return CharacterConfigData