---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/22 14:40
---
---@class LoginResponse
local LoginResponse = class("LoginResponse")
local this = LoginResponse
function LoginResponse:ctor()
    ---@type string
    self.token = string.empty
    ---@type number
    self.uid = 0
    ---@type string
    self.userName = string.empty
    ---@type number
    self.goldNum = 0
    ---@type number
    self.premiumDiamondNum = 0
    ---@type number
    self.diamondNum = 0
end

---@param userName string
function LoginResponse:new(token, uid, userName, goldNum, premiumDiamondNum, diamondNum)
    --local obj = LoginResponse.New()
    -- local obj = {
    self.token = token                         ---java.lang.String
    self.uid = uid                             -- long
    self.userName = userName                   ---java.lang.String
    self.goldNum = goldNum                     -- long
    self.premiumDiamondNum = premiumDiamondNum -- long
    self.diamondNum = diamondNum               -- long
    -- }
    -- setmetatable(obj, self)
    -- self.__index = self
    return self
end

function LoginResponse:protocolId()
    return 1001
end

function LoginResponse:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function LoginResponse:read(data)
    -- local jsonString = buffer:readString()
    -- ---字节读取器中存放字符
    -- local data = JSON.decode(jsonString)
    local jsonData = LoginResponse:new(
        data.token,
        data.uid,
        data.userName,
        data.goldNum,
        data.premiumDiamondNum,
        data.diamondNum)
    return jsonData
end

return LoginResponse
