---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/4 23:19
---


ByteBuffer = require("Game.Net.LuaProtocol.Buffer.ByteBuffer")

---初始化
require("Game.Cache.LoginCacheData")


require("Game.Net.ServerData.ServerDataManager")

PacketDispatcher = require("Game.Net.PacketDispatcher")

ProtocolManager = require("Game.Net.ProtocolManager")
