---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/4 23:19
---

------------------ service 初始化 ------------------

LoginService = require("Game.Net.Service.LoginService")
require("Game.Net.Service.PhysicalPowerService")

------------------ service 初始化 end------------------



ByteBuffer = require("Game.Net.LuaProtocol.Buffer.ByteBuffer")

---初始化
require("Game.Cache.LoginCacheData")


require("Game.Net.ServerData.ServerDataManager")

PacketDispatcher = require("Game.Net.PacketDispatcher")

ProtocolManager = require("Game.Net.ProtocolManager")
