--- 网络包注册
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/22 13:10
---
PacketDispatcher = {}
_receiversMap = {}
PacketDispatcher.Event = {
    OnConnect = "NetDispatcher.Event.OnConnect",
    OnDisConnect = "NetDispatcher.Event.OnDisConnect",
}
--- 链接建立通知lua
function OnConnectServer(url)
    printDebug("网络链接链接成功，Url：【" .. url .. "]")
    ---链接成功
    GlobalEventSystem:Fire(PacketDispatcher.Event.OnConnect, url)
end

function OnDisConnectFromServer()
    printDebug("Game server disconnected!!")
    GlobalEventSystem:Fire(NetDispatcher.Event.OnDisConnect)
end

function OnReceiveLineFromServer(bytes)
    local packet = readBytes(bytes)
    NetDispatcher.Receive(packet)
end
function PacketDispatcher:SendMessage(bytes)
    netManager:SendMessage(bytes)
end
function PacketDispatcher:Init()
    local beans = {
        "Game.Login.LoginNetController"
    }
    for i, v in ipairs(beans) do
        local ctrl = require(v)
        if type(v) ~= "boolean" then
            ctrl:Init()

        end
    end

end

function PacketDispatcher:Receive(packet)
    GlobalEventSystem:Fire(packet.protocolId(), packet)
end

