---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/21 14:31
---

local serverMessageWrite = BaseClass()

serverMessageWrite.protocolId = 0
serverMessageWrite.packet = {}

function serverMessageWrite:new(protocolId, packet)
    --local server = serverMessageWrite.New()
    --server.protocolId = protocolId
    --server.packet = packet
    return {
        protocolId = protocolId,
        packet = packet
    }
end

return serverMessageWrite