---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/28 10:13
---
local apiHandler = BaseClass()
apiHandler.Const = {
    Event = {
        OnBeforeSendDelegate = "apiHandler.OnBeforeSendDelegate",
        OnCompleteDelegate = "apiHandler.OnCompleteDelegate",
        OnErrorDelegate = "apiHandler.OnErrorDelegate",
        OnResponseDelegate = "apiHandler.OnResponseDelegate",
    }
}
local apiQueue = list.new()

local AuthToken = ""
local baseUrl = nil

function apiHandler.SetUp(baseUri, authToken)
    baseUrl = CS.System.Uri(baseUri)
    AuthToken = authToken
end

function apiHandler.Request(api)
    --- api 地址
    local relativePath = api.Path
    local data = nil
    local request=require("Game.Http.src.httpClient.apiRequest")
end

return apiHandler