---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/27 13:37
---

local apiRequest = BaseClass()
apiRequest.Uri = nil
apiRequest.Method = nil
apiRequest._watch = CS.System.Diagnostics.Stopwatch

local _bhRequest = nil
local _onBeforeSend = nil
local _onSuccess = nil
local _onError = nil
local _onComplete = nil

function apiRequest.Init(method, uri, data, onBeforeSend, onSuccess, onError, onComplete)
    apiRequest.Uri = uri
    apiRequest.Method = method
    _bhRequest = CS.BestHTTP.HttpRequest(apiRequest.Uri, apiRequest.Method)
    _bhRequest:SetHeader("Accept-Encoding", "gzip")
    _bhRequest:SetHeader("App-Version", CS.UnityEngine.Application.version)
    _bhRequest:SetHeader("User-Agent", CS.ZJYFrameWork.Net.UserAgent.Value)
    _bhRequest:SetHeader("Content-Type", "application/json")
    _bhRequest.RawData = data
    _onBeforeSend = onBeforeSend
    _onSuccess = onSuccess
    _onError = onError
    _onComplete = onComplete
end

function apiRequest.HandleResponse(originalBhRequest, bhResponse)
    apiRequest._watch.Stop()
    local elapsedMsec = apiRequest._watch.ElapsedMilliseconds
    local apiRespnse = require("Game.Http.src.httpClient.apiResponse"):New()
    apiRespnse.new(apiRequest, bhResponse, elapsedMsec)

    if apiRespnse.IsSuccess() then
        if _onSuccess ~= nil then
            _onSuccess(apiRespnse)
        end
    else
        if _onError ~= nil then
            _onError(apiRespnse)
        end
    end
    if _onComplete~=nil then
        _onComplete(apiRespnse)
    end
end

function apiRequest.Send()
    if _onBeforeSend ~= nil then
        _onBeforeSend(apiRequest)
    end
    apiRequest._watch = CS.System.Diagnostics.Stopwatch()
    apiRequest._watch.Start()

    _bhRequest.Send()
end

return apiRequest
