---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/27 13:37
---

local ApiRequest = CS.ZJYFrameWork.Net.ApiRequest

local apiRequest = BaseClass()
apiRequest.Uri = nil
apiRequest.Method = nil
apiRequest._watch = CS.System.Diagnostics.Stopwatch

local _bhRequest = nil
function apiRequest.Init(method, uri, onBeforeSend, data, onSuccess, onError, onComplete)
    apiRequest.Uri = CS.System.Uri(uri)
    apiRequest.Method = method
    _bhRequest = CS.BestHTTP.HttpRequest(apiRequest.Uri, apiRequest.Method)
    _bhRequest:SetHeader("Accept-Encoding", "gzip")
    _bhRequest:SetHeader("App-Version", CS.UnityEngine.Application.version)
    _bhRequest:SetHeader("User-Agent", CS.ZJYFrameWork.Net.UserAgent.Value)
    _bhRequest:SetHeader("Content-Type", "application/json")
    _bhRequest.RawData = data


end
function apiRequest.HandleResponse(originalBhRequest, bhResponse)
    _watch.Stop()
    local elapsedMsec = _watch.ElapsedMilliseconds;

end
return apiRequest