--- http 客户端
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/26 17:27

---初始化 http
local ApiRequest = CS.ZJYFrameWork.Net.ApiRequest
local http = require("Game.Http.src.socket.http")
---http 客户端
--local httpC = http.new()
---@class httpClient
local httpClient = {}
function httpClient.Init()

    httpClient.setUri(global.settingManager:GetHttpsBase())
    httpClient.setHttp()
end

---@param url string
local url = ""

---@param uri string
function httpClient.setUri(uri)
    url = uri
end

function httpClient.setHttp()
end

return httpClient




