---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/13 16:27
---


LoginPanelView={}

function LoginPanelView:Init(view)
    self.LoginPart=view:GetObjType("LoginPart") or CS.UnityEngine.GameObject
    self.LoginPartView=view:GetObjType("LoginPartView")or CS.ZJYFrameWork.UISerializable.LoginPartView
end

return LoginPanelView