---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/13 16:27
---


local LoginPanelView=BaseClass()
local _UIView={}
function LoginPanelView:Init(view)
    print("LoginPanelView:Init",view)
    _UIView= view:GetComponent("UIView")
    self.LoginPart=_UIView:GetObjType("LoginPart") or CS.UnityEngine.GameObject
    print("LoginPanelView:Init  self.LoginPart", self.LoginPart)

    self.LoginPartView=_UIView:GetObjType("LoginPartView")or CS.ZJYFrameWork.UISerializable.LoginPartView
    print("LoginPanelView:Init  self.LoginPartView", self.LoginPartView)
end

return LoginPanelView