--- 初始化相关函数
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/16 19:33
---
print("Game Main working...")
print("Game Main Init...")
Debug = 0

function IsDebug(debug)
    Debug = debug
end
function printDebug(str)
    if Debug > 1 then
        print(str)
    end
end

