---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/11 19:33
---

function LuaMain()
    CS.Debug.Log("LuaMain")
    LoginUIModelView:Init()
end

function StartGame()
    CS.Debug.Log("StartGame")
end