---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/11 19:33
---

function LuaMain()
    log.log("LuaMain")

end

function StartGame()
    CS.Debug.Log("StartGame")
end
timestamp = 0
function SetNowTime(nowTime)
    timestamp = nowTime

end


---这个是不带任何参数
function EventSystemAction(name)
    GlobalEventSystem:Fire(name)
end




