---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/11 19:33
---

function LuaMain()
   log.log("LuaMain")
    UIComponentManager.InitUIModelComponent()
end

function StartGame()
    CS.Debug.Log("StartGame")
end
local Game={}
function Game:Init()

end
