---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/24 14:35
---
---@class LoginTapToStartRequest
local LoginTapToStartRequest = class("LoginTapToStartRequest")
local this = LoginTapToStartRequest
function LoginTapToStartRequest:ctor()
    self.clientName = string.empty
end

function LoginTapToStartRequest:new(clientName)
    this.clientName = clientName
    return this
end

function LoginTapToStartRequest:protocolId()
    return 1013
end

function LoginTapToStartRequest:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or LoginTapToStartRequest
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function LoginTapToStartRequest:read(data)
    return LoginTapToStartRequest:new()
end

return LoginTapToStartRequest
