--- 登录面板
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/15 19:09
---
---@class LoginPartView:UIBaseView
local LoginPartView = class("LoginPartView", UIBaseView())

function LoginPartView:ctor(view)
	self.LoginPart = view:GetObjTypeStr("LoginPart") or UnityEngine.GameObject
	self.LoginBtn = view:GetObjTypeStr("LoginBtn_Button") or UnityEngine.UI.Button
	self.RegisterBtn = view:GetObjTypeStr("RegisterBtn_Button") or UnityEngine.UI.Button
	self.account = view:GetObjTypeStr("account") or UnityEngine.UI.InputField
	self.password = view:GetObjTypeStr("password") or UnityEngine.UI.InputField
end

function LoginPartView:OnShow()
	self.LoginPart:SetActive(true)
	self.account.text = ""
	self.password.text = ""
end

function LoginPartView:OnHide()
	self.LoginPart:SetActive(false)
end

return LoginPartView
