---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/7/6 13:51
---
local SpringContext = require("NameSpace.ZJYFrameWork.Spring.Core.Springtext")

local cs = require("NameSpace.ZJYFrameWork.Scheduler")
local SchedulerManagerBeanString = "ZJYFrameWork.Hotfix.Common.PlayerUserCaCheData"

local CsScheduler = {
    SchedulerManager = cs.SchedulerManager,
}
local Common = {
    SchedulerManager = function()
        return SpringContext.GetBean(SchedulerManagerBeanString) or CsScheduler.SchedulerManager
    end,
}
---@class SchedulerManager
SchedulerManager=class("SchedulerManager")

function SchedulerManager:AddEventSystemAction(action)
    Common.SchedulerManager():AddEventSystemAction(action)
end

function SchedulerManager:SubEventSystemAction(action)
    Common.SchedulerManager():SubEventSystemAction(action)
end
