---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/24 下午10:59
---

GConfig = {}
-------------------------------------------------------------------------------------------
-- 关卡配置
-------------------------------------------------------------------------------------------
GConfig.MapID =
{
    Login = 140001,   -- 登录
    Lobby = 140002,   -- 大厅（创角）
    Rookie = 140003,  -- 新手关卡
    PVPLobby = 150002, -- PVP大厅
}

GConfig.MapNameIDList =
{
    [GConfig.MapID.Login] = "LoginScene",
}

