---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/16 下午10:13
---

MSG_NET_CODE = {
    MSG_NET_CODE_None = 0,

    --- 心跳 包 高频 发包
    MSG_NET_CODE_CSPingReq = 103,
    MSG_NET_CODE_SCPongRsp = 104,
    
    
}