require("frameWork.library.ClassLibraryMap")
require("common.include")
require("define.Include")
require("frameWork.gameStage.gameBaseStage")
require("frameWork.services.serviceBase")
require("frameWork.services.eventService.eventService")
require("frameWork.services.registerNativeServices")
require("frameWork.services.serviceManager")

require("frameWork.services.asset.assetDataEnum")

require("frameWork.mvc.stateUIControl")
require("frameWork.mvc.stateGameControl")
require("frameWork.mvc.stateEnum")
require("frameWork.mvc.frostUIMediator")
require("frameWork.mvc.UIBase")
require("frameWork.mvc.moduleBase")
require("frameWork.mvc.frostUIPrefab")
require("frameWork.mvc.uiPrefabClassAsync")
