---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/22 19:46
---

--- net
global.netManager = CS.ZJYFrameWork.Spring.Core.SpringContext.GetBean("ZJYFrameWork.Net.NetManager") or CS.ZJYFrameWork.Net.NetManager
--- CommonController
global.CommonController = CS.ZJYFrameWork.UISerializable.Common.CommonController
--- settingManager 当前
global.settingManager=CS.ZJYFrameWork.Spring.Core.SpringContext.GetBean("ZJYFrameWork.Setting.SettingManager") or CS.ZJYFrameWork.Net.SettingManager