---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/22 19:46
---

--- net
global.netManager = CS.ZJYFrameWork.Spring.Core.SpringContext.GetBean("ZJYFrameWork.Net.NetManager") or CS.ZJYFrameWork.Net.NetManager
--- CommonController
global.CommonController = CS.ZJYFrameWork.UISerializable.Common.CommonController
--- settingManager 当前
---@class CS.ZJYFrameWork.Net.SettingManager
---@field GetHttpsBase string 基础https的url
---@field GetWebSocketBase string 基础websocket请求url
---@field GetAssetBundleUrl string  AssetBundle Url
---@field GetSelectHostType table
---@field Save boolean 是否保存游戏配置成功
---@field GetAllSettingNames table 所有游戏配置项的名称
---@field HasSetting  boolean 检查是否存在指定游戏配置项
---@field GetString string 从指定游戏配置项中读取字符串值
---@field SetString any 向指定游戏配置项写入字符串值
global.settingManager=CS.ZJYFrameWork.Spring.Core.SpringContext.GetBean("ZJYFrameWork.Setting.SettingManager") or CS.ZJYFrameWork.Net.SettingManager