---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/13 23:13
---
UIBaseView=require("Common.UI.UIBaseView")
UIBaseModule=require("Common.UI.UIBaseModule")

UIConfigEnum=require("Common.UI.UIConfigEnum")
LoginUIModelView=require("Game.Login.LoginUIModelView")
GameMainUIModelView=require("Game.UI.GameMain.ModelView.GameMainModelView")