---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/16 0:12
---

local UINotifEnum={
    --- 打开 界面 
    OPEN_GAMEMAIN_PANEL="OPEN_GAMEMAIN_PANEL",
    CLOSE_GAMEMAIN_PANEL="CLOSE_GAMEMAIN_PANEL",
    TIME_GAMEMAIN_PANEL="TIME_GAMEMAIN_PANEL"
}

return UINotifEnum