---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/16 0:12
---

local GameMainConfig = {
    ---预制体名字
    prefabName = "GameMainPanel",
    --- 当前会生成在那一层
    canvasType = UIConfigEnum.UICanvasType.UI,
    sortType = UIConfigEnum.UISortType.First,
    --- 当前 UI 交互事件 消息
    eventNotification = {
        --- 打开 界面
        OPEN_GAMEMAIN_PANEL = "OPEN_GAMEMAIN_PANEL",
        --- 关闭界面
        CLOSE_GAMEMAIN_PANEL = "CLOSE_GAMEMAIN_PANEL",
        --- 时间显示
        TIME_GAMEMAIN_PANEL = "TIME_GAMEMAIN_PANEL",
        --- 面板数据显示
        SHOW_GAMEMAIN_DATAPANEL = "SHOW_GAMEMAIN_DATAPANEL"
    }
}

return GameMainConfig