---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/16 0:11
---

--- UI Model View
local GameMainUIModelView = BaseClass(UIBaseModule).New()
--- @class GameMainView
--- @return GameMainView
local UINotifEnum = GameMainConfig

--- 初始化 UI Model View
function GameMainUIModelView:Init()
    CS.Debug.Log("GameMainUIModelView Init")
    self.GameMainUIPanel = require("Game.GenerateScripts.UIModules.GameMainUIPanelView").New()
    self.GameMainUIView = require("Game.UI.GameMain.View.GameMainView")
    GameMainUIModelView.base = UIBaseModule.Create("GameMainUIPanel", UIConfigEnum.UISortType.Last,
            UIConfigEnum.UICanvasType.UI, self.GameMainUIView, self.GameMainUIPanel)
    GameMainUIModelView.base.InstanceOrReuse()

end
--- UI 通知事件
---@return table
function GameMainUIModelView:Notification()
    return UINotifEnum
end

function GameMainUIModelView:NotificationHandler(_eventNotification)
    if _eventNotification.GetEventName==UINotifEnum.OPEN_GAMEMAIN_PANEL then
        if GameMainUIModelView.base.isResuse then
            GameMainUIModelView.base:InstisResuseanceOrReuse()
        else
            GameMainUIModelView:Init()
        end
    end
    
end


return GameMainUIModelView