--- http 初始化 init
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/26 17:14
---
--http = require("Game.Http.src.socket.http")

--if http ~= nil then
--    printDebug("文件读取到", http)
--end