--- 全局 服务 配置路径
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangJIngYi.
--- DateTime: 2024/7/1 23:49
---

return {
    "application.app.framework.Schedule.ScheduleService",  ---定时器服务
}
