---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/2 下午11:36
---

---@class ServiceManager
local ServiceManager = class("ServiceManager")

function ServiceManager:ctor()

end

function ServiceManager:Initialize()
    local tListServiceConfigs = require("application.app.framework.services")
    for tIndex, tServiceFilePath in ipairs(tListServiceConfigs) do
        PrintDebug("%s \t Load service class with %s", self.__classname, tServiceFilePath)
        local tServiceClass = require(tServiceFilePath)
        if not tServiceClass or not IsChildOfClass(tServiceClass, "ServiceBase") then
            PrintError("%s \t Get service class failed, with \t %s", self.__classname, tServiceFilePath)
            goto continue
        end
        -- 先实例化服务类，用于调用后续函数，如果中途失败则不缓存创建的实例，通过Lua的GC自动清理
        local tServiceInstance = tServiceClass()
        local tServiceConfig = tServiceInstance:GetConfig()
        if not tServiceConfig or not tServiceConfig.name then
            PrintError("%s Get service class config failed, with \t %s \t %s", self.__classname, tServiceFilePath, table.toString(tServiceConfig))
            goto continue
        end
        local tServiceName = tServiceConfig.name
        -- 检查全局名称是否已注册
        if IsDefine(tServiceName) then
            PrintError("%s \t Already has global variable with name \t %s", self.__classname, tServiceName)
            goto continue
        end
        -- 创建服务类的实例
        PrintDebug("%s \t Create service instance with \t %s \t %s \t %s", self.__classname, tServiceName, tServiceFilePath)
        tServiceInstance:Initialize()
        Define(tServiceName, tServiceInstance)
        :: continue ::
    end
end

return ServiceManager