---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/5/22 下午3:46
---@class AcquireCharacterRequest
local AcquireCharacterRequest = class("AcquireCharacterRequest")
function AcquireCharacterRequest:ctor()

end
function AcquireCharacterRequest:protocolId()
    return 1045
end
function AcquireCharacterRequest:new()

end
function AcquireCharacterRequest:write()
    local data = {
        protocolId = self:protocolId(),
        packet = { }
    }
    local jsonStr = JSON.encode(data)
    return jsonStr
end
return AcquireCharacterRequest