---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/5/25 上午12:41
---
---@class CharacterEquipmentIDData
local CharacterEquipmentIDData = class("CharacterEquipmentIDData")
function CharacterEquipmentIDData:ctor()
    --- 装备id
    ---@type number 装备id
    self.equipmentId = 0;
    --- 在数据库中存放的id
    ---@type number
    self.equipmentFindId = 0;
end
--- 返回装备id
---@return number
function CharacterEquipmentIDData:getEquipmentId()
    return self.equipmentId;
end

---@param equipmentId number 装备id
---@param equipmentFindId number 在数据库中存放的id
function CharacterEquipmentIDData:new(equipmentId, equipmentFindId)
    self.equipmentId = equipmentId;
    self.equipmentFindId = equipmentFindId;
    return self
end
--- 返回 具体类数据
---@param data CharacterEquipmentIDData 服务器解析数据
---@return CharacterEquipmentIDData
function CharacterEquipmentIDData:read(data)
    local readData = self:new(data.equipmentId, data.equipmentFindId)
    return readData
end

return CharacterEquipmentIDData