---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/5/25 上午12:35
---
---@class CharacterBaseData
local CharacterBaseData = class("CharacterBaseData")
function CharacterBaseData:ctor()
    this.id = id;
    this.roleID = roleID;
    this.quantity = quantity;
    this.lv = lv;
    this.nowMaxLv = nowMaxLv;
    this.nowExp = nowExp;
    this.nowMaxExp = nowMaxExp;
    this.lvQuantity = lvQuantity;
    this.maxLvQuantity = maxLvQuantity;
    this.equipmentList = equipmentList;
    this.characterWeaponIDData = characterWeaponIDData;
    this.elementType = elementType;
    this.elementNum = elementNum;
end

return CharacterBaseData;