---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/7 下午8:47
---
require("debug.luaPanda").start()
Debug = 0
ConfigurationDevice = {}
CS = CS
local function Init()
    Debug = CS.FrostEngine.SettingsUtils.DebugConfig()
end
Init()
Global = {}
local __g = _G


function __G__TRACKBACK__(exceptionMsg)
    local msg = string.format("[%d] %s\n", handleLuaExceptionIdx, tostring(exceptionMsg))
    local str = "LUA ERROR: " .. msg
    local strMsg="----------------------------------------\n"..str.."\n"..debug.traceback().."\n----------------------------------------"
    if FrostLogE then
        FrostLogE(strMsg)
    else
        print(strMsg)
    end

    -- 若报错信息与上一条相同，忽略显示
    --if lastLuaExceptionMsg == exceptionMsg then
    --    return
    --end
    lastLuaExceptionMsg = exceptionMsg
    handleLuaExceptionIdx = handleLuaExceptionIdx + 1

    --handleLuaException(msg)
    if Debug < 1 then
        -- 正式线上不显示详细信息
        str = str .. debug.traceback() .. "\n"
    end
end
local function main()
    print("main 函数")
end
local status, msg = pcall(main, __G__TRACKBACK__)
if not status then
    print('xpcall robot main error' .. type(status) .. "," .. msg)
end

function LuaInit()
    GameModule = CS.FrostEngine.GameModule
    SettingModule = CS.FrostEngine.ModuleSystem.GetModule("SettingModule")
    RootModules = CS.FrostEngine.ModuleSystem.GetModule("RootModules")
    math.randomseed(os.time())
    require("game.Include")
    ServiceManager:Initialize()
    NetMessageService:Connect(SettingModule.ServerSettings.ApiWebSocketUrl)
end

function LuaTick()
end