---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/13 下午11:36
---

local DataCenterConfig = {
    --
    --TemplateDataCentreName = {
    --    ClassName = "TemplateDataCentreClassName"
    --    IsGlobal = boolean, 是否为全局数据
    --    Paths = -- All files this data centre needed
    --    {
    --          "Game.Data.Template.TemplateCentreFile1",
    --          "Game.Data.Template.TemplateCentreFile2",
    --    }
    --},
    --
    LoginData = {
        ClassName = "LoginData",
        Paths = {
            "game.websocket.login.LoginData"
        }
    }
}