---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/13 下午11:36
---

local DataCenterConfig = {
    --
    --TemplateDataCentreName = {
    --    ClassName = "TemplateDataCentreClassName"
    --    IsGlobal = boolean, 是否为全局数据
    --    Paths = -- All files this data centre needed
    --    {
    --          {
    --             ClassName = "TemplateDataCentreClassName",
    --             Path = "Game.Data.Template.TemplateCentreFile1",
    --          }
    --    }
    --},
    --
    LoginData = {
        ClassName = "LoginData",
        Paths = {
            
        }
    }
}