--- 数据中心 基类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/13 下午11:45
---

---@class WebSocketDataCentreBase
local WebSocketDataCentreBase = require("WebSocketDataCentreBase")

function WebSocketDataCentreBase:ctor()
    --- 数据中心服务
    self._dataCenterService = false
end

---------------------------------------------------------------------
--- 初始化 
--- @param inDataCenter
---------------------------------------------------------------------
function WebSocketDataCentreBase:Initialize(inDataCenter)
    self._dataCenterService = inDataCenter
end

_G.WebSocketDataCentreBase = WebSocketDataCentreBase
return WebSocketDataCentreBase