--- 数据中心 基类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/13 下午11:45
---

---@class WebSocketDataCentreBase
local WebSocketDataCentreBase = Class("WebSocketDataCentreBase")

function WebSocketDataCentreBase:ctor()
    --- 数据中心服务
    self._dataCenterService = false
end

-------------------------------------------------------------------------------------------
--- 初始化 
--- @param inDataCenter DataCentreService
-------------------------------------------------------------------------------------------
function WebSocketDataCentreBase:Initialize(inDataCenter)
    self._dataCenterService = inDataCenter
    self:vInitialize()
end

function WebSocketDataCentreBase:SetDataCentre(dataCentre)
    self._dataCentre = dataCentre
end

---@return DataCentreService
function WebSocketDataCentreBase:GetDataCentre()
    return self._dataCentre
end

-------------------------------------------------------------------------------------------
--- 子类覆盖，进行初始化逻辑
-------------------------------------------------------------------------------------------
function WebSocketDataCentreBase:vInitialize()
end

-------------------------------------------------------------------------------------------
-- 子类覆盖，进行反初始化逻辑
-------------------------------------------------------------------------------------------
function WebSocketDataCentreBase:vDeinitialize()
end
return WebSocketDataCentreBase