---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/29 下午9:52
---

GlobalEnum = {
    EInvalidDefine = {
        ID = -1,
        Alpha = 0,
    }
}