---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/24 14:35
---
---@class LoginTapToStartRequest
local LoginTapToStartRequest = {}
local json = require("Common.json")

function LoginTapToStartRequest:new()
    local obj = {}
    setmetatable(obj, self)
    self.__index = self
end

function LoginTapToStartRequest:protocolId()
    return 1013
end

function LoginTapToStartRequest:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or LoginTapToStartRequest
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = json.encode(message)
    buffer:writeString(jsonStr)
end

function LoginTapToStartRequest:read(buffer)
    local jsonString = buffer:readString()
    ---字节读取器中存放字符
    local data = json.decode(jsonString)
    return LoginTapToStartRequest:new()
end

return LoginTapToStartRequest