---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/23 13:38
---
---@class LoginRequest
LoginRequest = {}
local json = require("Common.json")

---@param account string 用户名
---@param password string 密码
function LoginRequest:new(account, password)
    local obj = {
        account=account, -- java.lang.String
        password=password -- java.lang.String
    }
    setmetatable(obj,self)
    self.__index=self
end

return LoginRequest