---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/22 14:40
---
---@class LoginResponse
LoginResponse = {}
local json = require("Common.json")
---@param token string
---@param uid number
---@param userName string
---@param goldNum number 金币
---@param premiumDiamondNum number 付费钻石 一般充值才有，付费钻石转换成普通钻石
---@param diamondNum number 普通钻石 由付费钻石转换成普通钻石，比例为 1:1
function LoginResponse:new(token, uid, userName, goldNum, premiumDiamondNum, diamondNum)
    local obj = {
        token = token, ---java.lang.String
        uid = uid, -- long
        userName = userName, ---java.lang.String
        goldNum = goldNum, -- long
        premiumDiamondNum = premiumDiamondNum, -- long
        diamondNum = diamondNum -- long
    }
    setmetatable(obj, self)
    self.__index = self
    return obj
end
function LoginResponse:protocolId()
    return 1001
end

function LoginResponse:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or Error
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = json.encode(message)
    buffer:writeString(jsonStr)
end
function LoginResponse:read(buffer)
    local jsonString = buffer:readString()
    ---字节读取器中存放字符
    printDebug("LoginResponse:read(buffer) line 48" .. jsonString)
    local data = json.decode(jsonString)
    local jsonData = LoginResponse:new(data.packet.token,
            data.packet.uid,
            data.packet.userName,
            data.packet.goldNum,
            data.packet.premiumDiamondNum,
            data.packet.diamondNum)
    return jsonData
end
return LoginResponse