--- 
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.

--- DateTime: 2023/5/24 14:42
--- 登陆拦截器
---@class LoginTapToStartResponse
local LoginTapToStartResponse = {}

local json = require("Common.json")

function LoginTapToStartResponse:new(message, accessGame)

    local obj = {
        message = message, ---java.lang.String
        accessGame = accessGame, -- boolean
    }

    setmetatable(obj, self)
    self.__index = self
    return obj
end
function LoginTapToStartResponse:protocolId()
    return 1001
end

function LoginTapToStartResponse:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or LoginTapToStartResponse
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = json.encode(message)
    buffer:writeString(jsonStr)
end

function LoginTapToStartResponse:read(buffer)
    local jsonString = buffer:readString()
    ---字节读取器中存放字符
    local data = json.decode(jsonString)
    local jsonData = LoginTapToStartResponse:new(
            data.packet.message,
            data.packet.accessGame)
    return jsonData
end
return LoginTapToStartResponse