---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/24 0:22
---

---@class RegisterResponse
local RegisterResponse = {}
function RegisterResponse:new(error, mRegister)
    local obj = {
        error = error, -- java.lang.String
        mRegister = mRegister -- boolean
    }
    setmetatable(obj, self)
    self.__index = self
    return obj
end

function RegisterResponse:protocolId()
    return 1006
end

function RegisterResponse:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or RegisterResponse
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function RegisterResponse:read(buffer)
    local jsonString = buffer:readString()
    ---字节读取器中存放字符
    local data = JSON.decode(jsonString)
    return RegisterResponse:new(data.packet.error, data.packet.mRegister)
end

return RegisterResponse