---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/5/19 下午4:55
---

---@class CharacterNetController
local CharacterNetController = class("BagNetContorller")
---@type CharacterNetController
local instance = nil
function CharacterNetController:ctor()
    self.msg = {}
    ---@type table<number,CharacterConfigData>
    self.characterConfigList = nil;

end

function CharacterNetController:GetInstance()
    if not instance then
        instance = CharacterNetController()
    end
    return instance
end

--- 注册事件
function CharacterNetController:RegisterEvent()


end

---
--- @param characterConfigDataList table<number,CharacterConfigData>
function CharacterNetController:SetCharacterConfigResponse(characterConfigDataList)
    self.characterConfigList = characterConfigDataList
end

---  头部 按钮 点击事件回调相关
---@param packet table<number,CharacterConfigData>
function CharacterNetController:AtBagHeaderBtnHandlerServer(packet)
    WeaponNetController:SetWeaponUserEntityList(packet)
    UIGameEvent.BagHeaderWeaponBtnHandler()
end

return CharacterNetController