---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/13 下午11:57
---

local GameBattleFightManager=class("GameBattleFightManager")

--- 战斗中 运行 tick
function GameBattleFightManager:UpdateTick()
    
end


return GameBattleFightManager