---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/7/11 19:44
---

local EventBus = {}

function EventBus:Scan()
    
end
function SyncSubmit(eventString)
    if Debug > 0 then
        printDebug("执行事件，eventName:"..eventString)
    end
    GlobalEventSystem:Fire(eventString)
end

return EventBus