---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2024/7/25 17:44
---

---@class LoadingService:ServiceBase
local LoadingService = Class("LoadingService", ClassLibraryMap.ServiceBase)

function LoadingService:ctor()
    self._UILoadUpdate = CS.GameMain.UIDefine.UILoadUpdate
end

function LoadingService:vGetConfig()
    return {
        name = "LoadingService"
    }
end

function LoadingService:vInitialize()
    
end

function LoadingService:Show()
    CS.GameMain.UILoadMgr.Show(self._UILoadUpdate)
end

function LoadingService:Hide()
    CS.GameMain.UILoadMgr.HideAll()
end

return LoadingService

