--- 登录成功之后点击 开始游戏
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/12/10 21:43
---
---@class LoginTapToStartView:UIBaseView
local LoginTapToStartView = class("LoginTapToStartView", UIBaseView)
local SpringContext = require("NameSpace.ZJYFrameWork.Spring.Core.Springtext")

function LoginTapToStartView:Build(view)
	self.LoginStartButton = view:GetObjTypeStr("LoginStartButton") or CS.UnityEngine.UI.Button
	self.LoginStartMaxButton = view:GetObjTypeStr("LoginStartMaxButton") or CS.UnityEngine.UI.Button
	self.SteamLoginCanvasGroup = view:GetObjTypeStr("LoginStart_CanvasGroup") or CS.UnityEngine.CanvasGroup

	if self.LoginStartButton == nil then
		if Debug > 0 then
			printError("请检查[" .. view.name .. "]物体配置下面是否有[LoginStartButton]组件")
		end
	end
	self:SetListener(self.LoginStartButton, function()
		LoginService:LoginTapToStart()
	end)
	self:SetListener(self.LoginStartMaxButton, function()
		LoginUIController:OnClose()
	end)
end

function LoginTapToStartView:OnShow()
	UICommonViewController:GetInstance().LoadingRotate:OnClose()
	self.SteamLoginCanvasGroup.alpha = 1
	self.SteamLoginCanvasGroup.interactable = true
	self.SteamLoginCanvasGroup.ignoreParentGroups = true
	self.SteamLoginCanvasGroup.blocksRaycasts = true
end

function LoginTapToStartView:OnHide()
	if self.SteamLoginCanvasGroup.alpha < 1 then
		return
	end
	self.SteamLoginCanvasGroup.alpha = 0
	self.SteamLoginCanvasGroup.interactable = false
	self.SteamLoginCanvasGroup.ignoreParentGroups = false
	self.SteamLoginCanvasGroup.blocksRaycasts = false
end

function LoginTapToStartView:LoginSatrtGame()
	LoginUIController:OnClose()
	local ProcedureChangeScene = CS.ZJYFrameWork.Spring.Core.Springtext.GetBean("ProcedureChangeScene") or
		CS.ZJYFrameWork.Procedure.Scene.ProcedureChangeScene
	---跳转场景
	ProcedureChangeScene:ChangeScene(CS.ZJYFrameWork.Constant.SceneEnum.GameMain, "GameMain")
end

return LoginTapToStartView
