---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/13 15:52
---

local _core = require("NameSpace.ZJYFrameWork.Spring")

local Core={
    SpringContext=_core.Core.SpringContext
}

return Core