---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/28 14:56
---
local apiResponse = class("apiResponse")

function apiResponse:new(request, bhResponse, elapsedMilliseconds)
	self.Request = request
	self.bhResponse = bhResponse
	self.ElapsedMilliseconds = elapsedMilliseconds
	if type(bhResponse) == "nil" then
		self.StatusCode = 0
		self.StatusMessage = "Timeout"
		self.Headers = nil
		self.RawData = nil
	else
		self.StatusCode = bhResponse.StatusCode
		self.StatusMessage = bhResponse.Message
		self.Headers = bhResponse.Headers
		self.RawData = bhResponse.Data
	end
end

function apiResponse.IsSuccess()
	return (apiResponse.StatusCode >= 200 and apiResponse.StatusCode < 300) or apiResponse.StatusCode == 304
end

function apiResponse.IsTimeout()
	return apiResponse.StatusCode == 0
end

return apiResponse
