---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/13 16:11
---
local hotfix = require("NameSpace.ZJYFrameWork.HotfixInit")
local SpringContext = require("NameSpace.ZJYFrameWork.Spring.Core.Springtext")
local _common = {
    Common = hotfix.Common
}
local CsCommon = {
    PlayerUserCaCheData = _common.Common.PlayerUserCaCheData,
    PhysicalPowerCacheData = _common.Common.PhysicalPowerCacheData
}

local PlayerUserCaCheDataBeanString = "ZJYFrameWork.Hotfix.Common.PlayerUserCaCheData"
local PhysicalPowerCacheDataBeanString = "ZJYFrameWork.Hotfix.Common.PhysicalPowerCacheData"
local Common = {
    PlayerUserCaCheData = function()
        return SpringContext.GetBean(PlayerUserCaCheDataBeanString) or CsCommon.PlayerUserCaCheData
    end,
    PhysicalPowerCacheData=function() 
        return  SpringContext.GetBean(PhysicalPowerCacheDataBeanString) or CsCommon.PhysicalPowerCacheData
    end

}

return Common