---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/13 16:11
---
local hotfix = require("NameSpace.ZJYFrameWork.HotfixInit")
local SpringContext = require("NameSpace.ZJYFrameWork.Spring.Core.Springtext")
local _common = {
    Common = hotfix.Common
}
local CsCommon = {
    PlayerUserCaCheData = _common.Common.PlayerUserCaCheData
}

local PlayerUserCaCheDataBeanString = "ZJYFrameWork.Hotfix.Common.PlayerUserCaCheData"
local Common = {
    PlayerUserCaCheData = function()
        return SpringContext.GetBean(PlayerUserCaCheDataBeanString) or CsCommon.PlayerUserCaCheData
    end

}

return Common