PrintDebug("读取框架代码脚本")
FrostComponent = require("application.app.framework.frostEngine.frostComponent")
FrostObject = require("application.app.framework.frostEngine.frostObject")
FrostGameObject = require("application.app.framework.frostEngine.gameObject")
ServiceBase = require("application.app.framework.services.serviceBase")
