---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/14 下午2:52
---

---------------------------------------------------------------------
--- 服务的实例化
---------------------------------------------------------------------

return {

    "frameWork.schedule.scheduleService",       -- 定时器服务
    "frameWork.services.netMessage.netMessageService",   -- 网络
    "frameWork.services.gameStage.gameStageService",     -- 游戏阶段服务

    "frameWork.services.gameTime.gameTimeService",       -- 时间服务
    "frameWork.services.csNetwork.NetWrokService",       -- 网络服务
    "frameWork.services.sceneMap.SceneMapService",       -- 地图

    "frameWork.services.asset.assetService",       -- 资源

    "frameWork.mvc.mvcService",
    "frameWork.mvc.stateService",

}