---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/14 下午2:52
---

---------------------------------------------------------------------
--- 服务的实例化
---------------------------------------------------------------------

return {
    "frameWorker.csNetwork.NetWrokService",
    "frameWork.schedule.scheduleService",  -- 定时器服务
    "frameWorker.netMessage.NetMessageService", -- 网络
    "frameWorker.csNetwork.NetWrokService", -- 网络服务
}