---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/13 16:06
---


local _springContext = require("NameSpace.ZJYFrameWork.Spring.Core")

local SpringContext = {}

---@param beamString string
function SpringContext.GetBean(beamString)
    return _springContext.SpringContext.GetBean(beamString)
end

return SpringContext