--- 错误消息机制
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/19 18:55
---
local Error = {}

function Error:new(errorCode, errorMessage, module)
    local obj = {
        errorCode = errorCode, -- int
        errorMessage = errorMessage, -- java.lang.String
        module = module -- int
    }
    setmetatable(obj, self)
    self.__index = self
    return obj
end

function Error:protocolId()
    return 101
end


function Error:write(buffer, packet)

end




return Error
