---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/1/26 0:43
---

local I18nManager = class("I18nManager")
local i18st = "ZJYFrameWork.I18n.I18nManager"
function I18nManager:OnInit()
    ---@field GetValue function
    self.i18n = CS.ZJYFrameWork.Spring.Core.SpringContext.GetBean(i18st) or
            CS.ZJYFrameWork.I18n.I18nManager
end

---@param key string 字典主键
function I18nManager:GetString(key)
    local value = self.i18n:GetValue(key)
    if string.IsNullOrEmpty(value) then
        return string.empty
    end
    return value
end

return I18nManager
