--- 实现lua侧 UINotification 类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/17 16:49

---@class UINotification
local UINotification=class("UINotification")
function UINotification:new(name,Body)
    local obj = {
        eventName=name,
        eventBody=Body
    }
    setmetatable(obj, self)
    self.__index = self
    return obj
end
local eventName=''
local eventBody=nil


function UINotification:GetEventName()
    return eventName
end

function UINotification:GetEventBody()
    return eventBody
end

function UINotification:SetNotification(name,Body)
    eventName=name
    eventBody=Body
end

return UINotification