--- 通知界面的 控制器
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/11/27 15:08
---
---@class UICommonViewController
UICommonViewController = class("UICommonViewController")
function UICommonViewController:GetInstance()
    return UICommonViewController
end

function UICommonViewController:OnInit()
    self.viewPanel = UICommonView
    self.LoadingRotate = LoadingRotate
    self.viewPanel:OnInit(CS.ZJYFrameWork.UISerializable.Common.CommonController.Instance.snackbar.DialogPanelObject)
    self.LoadingRotate:OnInit(CS.ZJYFrameWork.UISerializable.Common.CommonController.Instance.loadingRotate)
end

function UICommonViewController:OnOpenDialog(buttonType, title, body, yesButtonText, noButtonText, onClick)
    self.viewPanel:OnOpen(buttonType, title, body, yesButtonText, noButtonText, onClick)
end
