---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/4 0:24
---

local LoadingConfig = {
    ---预制体名字
    prefabName = "LoadingPanel",
    --- 当前会生成在那一层
    canvasType = UIConfigEnum.UICanvasType.UI,
    sortType = UIConfigEnum.UISortType.First,
    --- 当前 UI 交互事件 消息
    eventNotification = {
        --- 打开Loading 界面
        OPEN_LOADINNG_UIPANEL = "OPEN_LOADINNG_UIPANEL",
        --- 关闭Loading 界面
        CLOSE_LOADING_UIPAENL = "CLOSE_LOADING_UIPAENL"
    }


}
return LoadingConfig