---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/4 0:14
---

local UILoadingUIModelView = BaseClass(UIBaseModule.New())
--- UI 主要逻辑
local UILoadingUIView = nil
--- UI组件绑定代码
local LoadingPanelView = nil

function LoginUIModelView:InitUI()

end

return UILoadingUIModelView
