---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/3 23:59
---

local UILoadingUIView = BaseClass(UIBaseView)

--- 初始化
function UILoadingUIView:OnInit()
    UILoadingUIView:OnShow()
end

--- 显示
function UILoadingUIView:OnShow()
    UILoadingUIView.GetUIView():OnShow()
    local viewPanel = UILoadingUIView.GetViewPanel()
    viewPanel.leftSlider_Slider.value = 0
    viewPanel.rightSlider_Slider.value = 0
end

---设置加载进度条
function UILoadingUIView:SetNowProgressNum(nums)
    local viewPanel = UILoadingUIView.GetViewPanel()
    viewPanel.leftSlider_Slider.value = nums
    viewPanel.rightSlider_Slider.value = nums
    local timeNum = string.format("%.0f%", (nums * 100));
    viewPanel.progressNum_Text.text = timeNum
end

return UILoadingUIView