---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/12 23:56
---
local _cs=CS
local csName={
    ZJYFrameWork=_cs.ZJYFrameWork
}

 
return csName