--[[
    DESCRIPTION DataCenter. Data of Login.
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2024/7/13 下午11:40
--]]

---@class LoginData:WebSocketDataCentreBase
local LoginData = Class("LoginData", _G.WebSocketDataCentreBase)

function LoginData:ctor()
end

return LoginData