--[[
    Generated by EmmyLua(https://github.com/EmmyLua)
    Created by zhangjingyi.
    DateTime: 2024/7/18 下午2:24
--]]

---@class ModuleBase
local ModuleBase = Class("ModuleBase")

function ModuleBase:ctor()
    self._localFilePaths = false -- 仅在存在非全生命周期
    self._mediator = {}
end

function ModuleBase:Create()
    
end

function ModuleBase:Destroy()
    
end

--- 重载 初始化
function ModuleBase:vOnInitializeModule()
end

--- 重载 反始化
function ModuleBase:vOnUninitializeModule()
end

--- 是否允许状态切换 
--- @param inSwitchType 
function ModuleBase:vOnGameStateAllowSwitch(inSwitchType,inCurrentState,inTargetState,inUserData)
    
end

return ModuleBase