---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/20 上午12:52
---

---@class UIPrefabClassAsync
local UIPrefabClassAsync = Class("UIPrefabClassAsync")

function UIPrefabClassAsync:ctor()
    -- UI 中间 层
    self._mediator = false

    -- 父类 的 prefabClass
    self._parentPrefabClass = false
    -- 父类组件
    self._parentTf = false
    
    -- prefab类 默认值
    self._prefabClassDef = false
    -- 参数 
    self._argument = false

    self._customID = GlobalEnum.EInvalidDefine.ID
    -- 样品
    self._style = false
    -- 层级
    self._layer = false
    -- 第一次
    self._insertFirst = false

    -- prefab的资源名
    self._assetName = false

    -- 操作参数
    self._operation = {}
end

return UIPrefabClassAsync
