---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/28 10:24
---

local httpManager = {}
local _handler=require("Game.Http.src.httpClient.apiHandler")
httpManager.UserAuth = {
    authToken = ""
}
httpManager.UserFromAttributeData = {
    channelCode = 0,
    platformId = "",
    sdkToken = "",
    printData = function()
        if Debug > 0 then
            printDebug("channelCode:" .. httpManager.UserFromAttributeData.channelCode .. ",platformId：" .. httpManager.UserFromAttributeData.platformId .. ",sdkToken:" .. httpManager.UserFromAttributeData.sdkToken)
        end
    end
}
function httpManager.new()

end

function httpManager.SetUserFromAttributeData(channelCode, platformId, sdkToken)
    httpManager.UserFromAttributeData.sdkToken = sdkToken
    if Debug > 0 then
        printDebug("channelCode:" .. channelCode .. ",platformId：" .. platformId)
    end
end