---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/24 0:22
---

---@class RegisterResponse
local RegisterResponse = class("RegisterResponse")

---@type RegisterResponse
local this = RegisterResponse
function RegisterResponse:ctor()
    self.error = nil
    self.mRegister = nil
end

function RegisterResponse:new(error, mRegister)
    self.error = error             -- java.lang.String
    self.mRegister = mRegister     -- boolean
    return self
end

function RegisterResponse:protocolId()
    return 1006
end

function RegisterResponse:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or RegisterResponse
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function RegisterResponse:read(data)
    -- local jsonString = buffer:readString()
    -- ---字节读取器中存放字符
    -- local data = JSON.decode(jsonString)
    return RegisterResponse:new(data.error, data.mRegister)
end

return RegisterResponse
