---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/7/5 19:09
---

---@class PhysicalPowerResponse
local PhysicalPowerResponse = {}

--- 创建协议体
---@param nowPhysicalPower number
---@param residueTime number
---@param maximumStrength  number
---@param maximusResidueEndTime number
---@param residueNowTime number
function PhysicalPowerResponse:new(nowPhysicalPower, residueTime, maximumStrength, maximusResidueEndTime, residueNowTime)
    local object = {
        nowPhysicalPower = nowPhysicalPower,
        residueTime = residueTime,
        maximumStrength = maximumStrength,
        maximusResidueEndTime = maximusResidueEndTime,
        residueNowTime = residueNowTime
    }
    setmetatable(obj, self)

    self.__index = self
    return obj
end

--- 返回当前协议id
---@return number 协议id
function PhysicalPowerResponse:protocolId()
    return 1024
end

--- 将数据包里面的数据装换成json 字符 写入字节流管理器
---@param buffer ByteBuffer
---@param packet
function PhysicalPowerResponse:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or PhysicalPowerResponse

    local message = {
        protocolId = data:protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

---  读取器 从字节流管理器中读取到对应字符
---@param buffer any
---@return table
function PhysicalPowerResponse:read(buffer)
    local jsonString = buffer:readString()
    ---@type {protocolId:number,packet:{nowPhysicalPower:number, residueTime:number, residueNowTime:number, maximumStrength:number, maximusResidueEndTime:number}}
    local data = JSON.decode(jsonString)
    local jsonData = PhysicalPowerResponse:new(data.packet.nowPhysicalPower,
            data.packet.residueTime,
            data.packet.maximumStrength,
            data.packet.maximusResidueEndTime,
            data.packet.residueNowTime)
    return jsonData
end

return PhysicalPowerResponse