---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/7/5 17:55
---

---@class PhysicalPowerRequest
local PhysicalPowerRequest={}

function PhysicalPowerRequest:new(uid)
    local object={
        uid=uid
    }
    setmetatable(object, self)

    self.__index = self
    return object
end

function PhysicalPowerRequest:protocolId()
    return 1023
end

---comment
---@param buffer ByteBuffer
---@param packet
function PhysicalPowerRequest:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or PhysicalPowerRequest
    local message = {
        protocolId = data:protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function PhysicalPowerRequest:read(buffer)
    local jsonStr = buffer:readString()
    ---@type {protocolId:number,packet:{uid:number}}
    local data = JSON.decode(jsonStr)
    local jsonData = PhysicalPowerRequest:new(data.packet.uid)
    return jsonData
end

return PhysicalPowerRequest