--- 使用体力的控制
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/21 16:52
---

---@class PhysicalPowerUsePropsRequest
local PhysicalPowerUsePropsRequest = {}
function PhysicalPowerUsePropsRequest:new(usePropNum)
    local obj = {
        usePropNum = usePropNum
    }
    setmetatable(obj, self)

    self.__index = self
    return obj
end

function PhysicalPowerUsePropsRequest:protocolId()
    return 1025
end

---comment
---@param buffer ByteBuffer
---@param packet
function PhysicalPowerUsePropsRequest:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or PhysicalPowerUsePropsRequest
    local message = {
        protocolId = data:protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function PhysicalPowerUsePropsRequest:read(buffer)
    local jsonStr = buffer:readString()
    ---@type {protocolId:number,packet:{usePropNum:number}}
    local data = JSON.decode(jsonStr)
    local jsonData = PhysicalPowerUsePropsRequest:new(data.packet.usePropNum)
    return jsonData
end

return PhysicalPowerUsePropsRequest

