--- 体力缓存
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/21 18:18
---

local cs = require("NameSpace.ZJYFrameWork.Hotfix.Common")
PhysicalPowerCacheData = {}

---返回 使用体力 所扣除 当前体力
function PhysicalPowerCacheData:getNowPhysicalPower()
    return cs.PhysicalPowerCacheData():getNowPhysicalPower()
end
