---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/13 16:21
---
local cs = require("NameSpace.ZJYFrameWork.Hotfix.Common")
---@class PlayerUserCaCheData
PlayerUserCaCheData = class("PlayerUserCaCheData")

function PlayerUserCaCheData:SetUIDValue(uid)
    cs.PlayerUserCaCheData().Uid = uid
end

function PlayerUserCaCheData:GetUID()
    return cs.PlayerUserCaCheData().Uid
end

function PlayerUserCaCheData:GetUseName()
    return cs.PlayerUserCaCheData().userName
end

function PlayerUserCaCheData:SetUseName(userName)
    cs.PlayerUserCaCheData().userName = userName
end

---@return number 免费钻石
function PlayerUserCaCheData:GetDiamondNumValue()
    return cs.PlayerUserCaCheData().DiamondNum
end

---@param num number 免费钻石 一般组合 为其它途径获取免费钻石加上付费钻石转换的总和
function PlayerUserCaCheData:SetDiamondNumValue(num)
    cs.PlayerUserCaCheData().DiamondNum = num
end

---返回付费钻石数量
---@return number 付费钻石数量
function PlayerUserCaCheData:GetPremiumDiamondNumValue()
    return cs.PlayerUserCaCheData().PremiumDiamondNum
end

--- 设置付费钻石
---@param num number 付费钻石数量
function PlayerUserCaCheData:SetPremiumDiamondNumValue(num)
    cs.PlayerUserCaCheData().PremiumDiamondNum = num
end

--- 返回金币数量
--- @return number 金币数量
function PlayerUserCaCheData:GetGoldNum()
    return cs.PlayerUserCaCheData().goldNum
end

--- 设置金币数量
---@param num number 自己的金币数量
function PlayerUserCaCheData:SetGoldNum(num)
    cs.PlayerUserCaCheData().goldNum = num
end

