---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zjy.
--- DateTime: 2023/5/20 19:04
---
local lua_type = type
local lua_tostring = tostring
local lua_pairs = pairs
local lua_ipairs = ipairs
local format = string.format
local strsub = string.sub
local tonumber = tonumber

CONSOLE_COLOR = {
    Dark_black = "#000000",
    Dark_Blue = "#00008b",
    Dark_Green = "#013220",
    Dark_Blue_Green = "#0d98ba",
    Dark_Red = "#ff0000",
    Dark_Purple = "#800080",
    Dark_Yellow = "#ffff00",
    Default = "#000000",
    Light_Black = "#000000",
    Light_Blue = "#00008b",
    Light_Green = "#013220",
    Light_Blue_Green = "#0d98ba",
    Light_Red = "#ff0000",
    Light_Purple = "#800080",
    Light_Yellow = "#ffff00",
    Light_White = "#ffffff",
}

function printLog(tag, fmt, ...)
    local t = {
        "[",
        string.upper(lua_tostring(tag)),
        "] ",
        format(lua_tostring(fmt), ...)
    }
    print(table.concat(t))
end
function printError(fmt, ...)

    printLog("ERR", setLogColor(CONSOLE_COLOR.Light_Red, fmt), ...)
    print(debug.traceback("", 2))
end

function printWarn(fmt, ...)
    if Debug < 1 then
        return
    end

    printLog("WARN", setLogColor(CONSOLE_COLOR.Light_Yellow, fmt), ...)
end

function printWarnStack(fmt, ...)
    if Debug < 1 then
        return
    end
    printLog("WARN", setLogColor(CONSOLE_COLOR.Light_Yellow, fmt), ...)
    print(debug.traceback("", 2))
end

function printInfo(fmt, ...)
    if Debug < 1 then
        return
    end

    printLog("INFO", setLogColor(CONSOLE_COLOR.Light_Green, fmt), ...)
end

function printDebug(fmt, ...)
    if Debug < 1 then
        return
    end
    printLog("DBG", setLogColor(CONSOLE_COLOR.Light_Blue_Green, fmt), ...)
end

function setLogColor(nColor, fmt)
    return "<color=" .. nColor .. ">" .. fmt .. "</color>"
end