PrintDebug("require lua script start")
--下面基础组件间的require有依赖顺序相关,闲着没事也别换顺序,要加新的往文件尾加就好
require("defines.app_defines")
require("common.util.str")
-- require("Common.util.helper")
require("common.util.time")

Mathf = require("common.unityEngine.Mathf")
Vector2 = require("common.unityEngine.Vector2")
Vector3 = require("common.unityEngine.Vector3")
Vector4 = require("common.unityEngine.Vector4")
Quaternion = require("common.unityEngine.Quaternion")
Color = require("common.unityEngine.Color")
Ray = require("common.unityEngine.Ray")
Bounds = require("common.unityEngine.Bounds")
RaycastHit = require("common.unityEngine.RaycastHit")
Touch = require("common.unityEngine.Touch")
LayerMask = require("common.unityEngine.LayerMask")
Plane = require("common.unityEngine.Plane")
Time = require("common.unityEngine.Time")
Object = require("common.unityEngine.Object")

require("common.system.coroutine")

require("common.class")

require("Common.util.stringUtil")
require("common.util.util")
require("Common.util.luaUtil")
list = require("common.util.list")
events = require("common.util.event")
require("Common.util.timer")
UpdateManager = require("common.UpdateManager")
JSON = require("common.json")
require("application.app.net.http.userAgent")
require("application.app.net.http.apiRequest")
require("application.app.net.http.apiResponse")
NetManager = require("application.app.net.webscoket.netManager")
GlobalEventSystem = require("common.util.EventSystem")
require("common.util.UIUtils")
require("application.app.cache.LoginCacheData")
require("application.app.cache.playerUserCaCheData")
ByteBuffer = require("application.app.net.webscoket.luaProtocol.buffer.byteBuffer")
Long = require("application.app.net.webscoket.luaProtocol.buffer.long")
ProtocolManager = require("application.app.net.webscoket.protocolManager")
PacketDispatcher = require("application.app.net.webscoket.packetDispatcher")
I18nManager = require("application.app.i18n.I18nManager")

GameEvent = require("application.app.event.gameEvent")
GameMainEvent = require("application.app.event.gameMainEvent")
UIGameEvent = require("application.app.event.uiGameEvent")


UIComponentManager = require("application.app.ui.UIComponentManager")

PrintDebug("require lua script end")
