printDebug("require lua script start")
--下面基础组件间的require有依赖顺序相关,闲着没事也别换顺序,要加新的往文件尾加就好
require("defines.app_defines")
require("commonn.util.str")
-- require("Common.util.helper")
require("commonn.util.time")

Mathf = require("commonn.unityEngine.Mathf")
Vector2 = require("commonn.unityEngine.Vector2")
Vector3 = require("commonn.unityEngine.Vector3")
Vector4 = require("commonn.unityEngine.Vector4")
Quaternion = require("commonn.unityEngine.Quaternion")
Color = require("commonn.unityEngine.Color")
Ray = require("commonn.unityEngine.Ray")
Bounds = require("commonn.unityEngine.Bounds")
RaycastHit = require("commonn.unityEngine.RaycastHit")
Touch = require("commonn.unityEngine.Touch")
LayerMask = require("commonn.unityEngine.LayerMask")
Plane = require("commonn.unityEngine.Plane")
Time = require("commonn.unityEngine.Time")
Object = require("commonn.unityEngine.Object")

require("commonn.system.coroutine")

require("commonn.class")

require("Common.util.stringUtil")
require("commonn.util.util")
require("Common.util.luaUtil")
list = require("commonn.util.list")
events = require("commonn.util.event")
require("Common.util.timer")
UpdateManager = require("commonn.UpdateManager")
JSON = require("commonn.json")
require("application.app.net.http.userAgent")
require("application.app.net.http.apiRequest")
require("application.app.net.http.apiResponse")
NetManager = require("application.app.net.webscoket.netManager")
GlobalEventSystem = require("commonn.util.EventSystem")
require("commonn.util.UIUtils")
require("application.app.cache.LoginCacheData")
require("application.app.cache.playerUserCaCheData")
ByteBuffer = require("application.app.net.webscoket.luaProtocol.buffer.byteBuffer")
Long = require("application.app.net.webscoket.luaProtocol.buffer.long")
ProtocolManager = require("application.app.net.webscoket.protocolManager")
PacketDispatcher = require("application.app.net.webscoket.packetDispatcher")
I18nManager = require("application.app.i18n.I18nManager")

GameEvent=require("application.app.event.gameEvent")
GameMainEvent=require("application.app.event.gameMainEvent")


UIComponentManager = require("application.app.ui.UIComponentManager")

printDebug("require lua script end")
