---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/4 11:11
---

local DialogConfig = {
    ButtonColor = {
        Yellow = CS.ZJYFrameWork.UI.UIModel.Dialog.ButtonColor.Yellow,
        Red = CS.ZJYFrameWork.UI.UIModel.Dialog.ButtonColor.Red,
    },
    ButtonType = {
        YesNo = CS.ZJYFrameWork.UI.UIModel.Dialog.ButtonType.YesNo,
        Yes = CS.ZJYFrameWork.UI.UIModel.Dialog.ButtonType.Yes,
    },
    Result = {
        OK = CS.ZJYFrameWork.UI.UIModel.Dialog.Result.OK,
        Yes = CS.ZJYFrameWork.UI.UIModel.Dialog.Result.Yes,
        No = CS.ZJYFrameWork.UI.UIModel.Dialog.Result.No,
    }

}

return DialogConfig