---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/13 16:17
---

---@class LoginView
local LoginView = BaseClass(UIBaseView.New())

function LoginView:OnInit()
    printInfo("LoginView:OnInit line 10")
    LoginView.GetViewPanel().LoginPartView:Build()
    LoginView.GetViewPanel().RegisterPartView:Build()
    LoginView.GetViewPanel().LoginTapToStartView:Build(nil)
    LoginView.GetViewPanel().LoginController:Build(LoginView:GetViewPanel().LoginPartView, LoginView:GetViewPanel().RegisterPartView, LoginView:GetViewPanel().LoginTapToStartView, LoginView)
    LoginView.GetViewPanel().LoginController:OnInit();


end

function LoginView:OnShow()
    printInfo("LoginView:OnShow line 21")

end

function LoginView:LoginStartGame()
    printDebug("LoginView:LoginStartGame() line 26")
    ---@type LoginPanelView
    local view = LoginView.GetViewPanel()
    view.LoginTapToStartView:LoginStartGame()
end
function LoginView:StartLoginTip()
    --coroutine.start()
end
return LoginView