--- 登录面板
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/15 19:09
---
---@class LoginPartView
local LoginPartView=BaseClass()

function LoginPartView:Build(view)

end






return LoginPartView;