---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/22 14:17
---

LoginNetController = BaseClass()
LoginConst = {
    Status = {

    },
    Event = {
        Login = 1001,
        Pong = 104,
        NetOpen = "LoginConst.Event.NetOpenEvent",
        StartLogin = "LoginConst.Event.StartLogin",
        LoginSucceed = "LoginConst.Event.LoginSucceed",
    }
}

function LoginNetController:Init()
    LoginNetController:InitEvents()
end
function LoginNetController:InitEvents()
    printDebug("LoginNetController:InitEvents() line 24")
    --GlobalEventSystem.all_event_dic[PacketDispatcher.Event.OnConnect] = function(url)
    --    LoginNetController:Connect(url)
    --end
    --GlobalEventSystem.all_event_dic[LoginConst.Event.Login] = function(data)
    --    LoginNetController:AtLoginResponse(data)
    --end

    GlobalEventSystem:Bind(PacketDispatcher.Event.OnConnect, function(url)
        LoginNetController:Connect(url)
    end)
    GlobalEventSystem:Bind(LoginConst.Event.Login, function(data)
        LoginNetController:AtLoginResponse(data)
    end)
    GlobalEventSystem:Bind(LoginConst.Event.Pong, function(data)
        LoginNetController:AtPong(data)
    end)
end
--- 网络打开
function LoginNetController:OnNetOpenEvent()
    CommonController.Instance.snackbar.OpenUIDataScenePanel(1, 1);
    CommonController.Instance.loadingRotate.OnClose();

end

function LoginNetController:AtLoginResponse(data)
    local response = data
    local token = response.token
    local uid = response.uid;
    ---@param userName string
    local userName = response.userName;
    if Debug > 0 then
        printDebug("[user:" .. userName .. "][token:" .. token .. "]" .. "[uid:" .. uid .. "]" .. "[goldNum:" .. response.goldNum .. "],[premiumDiamondNum:" .. response.premiumDiamondNum)
    end

end
function LoginNetController:Connect(url)
    printDebug("LoginNetController:Connect(url)line 46" .. type(url))
end

function LoginNetController:AtPong(data)
    printDebug("当前时间" .. data.time .. "," .. type(data.time))
    local timeNum = string.format("%.0f", (data.time / 1000));
    local time = os.date("%Y.%m.%d:%H.%M.%S", tonumber(timeNum))
    printDebug("当前时间" .. time)
end

function LoginNetController:AtLoginTapToStartResponse(data)
    local response = data
    if response.message ~= nil then
        printDebug("可以登陆" .. response.accessGame .. "," .. response.message)
    end
end

return LoginNetController