--- 登录面板
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/15 19:09
---
---@class LoginPartView:UIView
LoginPartView = class("LoginPartView", UIView)

function LoginPartView:Build(view)
    self:Close()
    self.LoginPart = view:GetObjType("LoginPart") or CS.UnityEngine.GameObject
    self.LoginBtn = view:GetObjType("LoginBtn_Button") or CS.UnityEngine.UI.Button
    self.RegisterBtn = view:GetObjType("RegisterBtn_Button") or CS.UnityEngine.UI.Button
    self.account = view:GetObjType("account") or CS.UnityEngine.UI.InputField
    self.password = view:GetObjType("password") or CS.UnityEngine.UI.InputField
end

function LoginPartView:Close()
    self.LoginPart = nil
    self.LoginBtn = nil
    self.RegisterBtn = nil
    self.account = nil
    self.password = nil
end
