--- 登录成功之后点击 开始游戏
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/12/10 21:43
---
---@class LoginTapToStartView:UIBaseView
local LoginTapToStartView = class("LoginTapToStartView", UIBaseView)

function LoginTapToStartView:Build(view)
    self.LoginStartButton = view:GetObjType("LoginStartButton") or CS.UnityEngine.UI.Button
    self.LoginStartMaxButton = view:GetObjType("LoginStartMaxButton") or CS.UnityEngine.UI.Button
    self.SteamLoginCanvasGroup = view:GetObjType("LoginStart_CanvasGroup") or CS.UnityEngine.CanvasGroup
end

return LoginTapToStartView
