---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/2 15:52

----------------start Config----------------
LoginConfig = require("Game.UI.Login.LoginConfig")

GameMainConfig = require("Game.UI.GameMain.ModelView.GameMainConfig")
UINotification = require("Game.Common.UINotification")
----------------end   Config----------------
