---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/2 15:52

require("Game.UI.NewUI.LuaUIObject")
require("Game.UI.NewUI.UIBaseView")
require("Game.UI.NewUI.UIView")

UIConfigEnum = require("Common.UI.UIConfigEnum")

----------------start Config----------------
LoginConfig = require("Game.UI.Login.LoginConfig")

GameMainConfig = require("Game.UI.GameMain.ModelView.GameMainConfig")
UINotification = require("Game.Common.UINotification")
----------------end   Config----------------
---
----------------start UI Component ----------------
UIComponentManager = require("Game.UI.UIComponentManager")

----------------end UI Component ----------------

------------******* start require file controller *******------------

require("Game.UI.GameMain.Controller.GameMainViewController")
require("Game.UI.CommonUI.UICommonView")
require("Game.UI.CommonUI.LoadingRotate")
require("Game.UI.CommonUI.UICommonViewController")

------------******* end   require file controller *******------------
