---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/4 11:09
---

--- CommonController
CommonController = CS.ZJYFrameWork.UISerializable.Common.CommonController
require("Game.CS.ZJYFrameWork.Execution.Executors")

DialogConfig = require("Game.CS.ZJYFrameWork.UI.Model.DialogEum")