---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/13 16:02
---

local _springContext = require("NameSpace.ZJYFrameWork.Spring.Core.Springtext")

local SpringContext = {}

function SpringContext.GetBean(beamString)
    return _springContext.GetBean(beamString)
end

return SpringContext