---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/4 23:15
---

local PlayerUserCaCheData = {
    --- 普通钻石 由付费钻石转换成普通钻石，比例为 1:1
    DiamondNum = 0,
    --- 金币
    goldNum = 0,
    --- 付费钻石 一般充值才有，付费钻石转换成普通钻石
    PremiumDiamondNum=0,
    --- 玩家UID
    Uid=0,
    --- 玩家的名字
    userName=""
}

return PlayerUserCaCheData