--- 实现lua侧 UINotification 类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/17 16:49


local UINotification=BaseClass().New()
local eventName=''
local eventBody=nil


function UINotification:GetEventName()
    return eventName
end

function UINotification:GetEventBody()
    return eventBody
end

function UINotification:SetNotification(name,Body)
    eventName=name
    eventBody=Body
end

return UINotification