---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/13 0:02
---

local Module=require("NameSpace.ZJYFrameWork.Hotfix.ModuleInit")

return Module.Login
