---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/16 下午9:51
---

--- @class GameTimeService:ServiceBase
local GameTimeService = Class("GameTimeService", ClassLibraryMap.ServiceBase)

function GameTimeService:ctor()
    self.time = ClassLibraryMap.Time
    -- 是否在发送 ping 
    self._IsSendPingStop = false
end

-------------------------------------------------------------------------------------------
-- 子类覆盖，进行返回类的静态配置数据
-------------------------------------------------------------------------------------------
function GameTimeService:vGetConfig()
    return
    {
        name = "GameTimeService",
    }
end

function GameTimeService:vInitialize()
    NetMessageService:ListenMessage(MSG_NET_CODE.MSG_NET_CODE_SCPongRsp, self, self.OnPongResponse)
end

function GameTimeService:OnConnected()
    ScheduleService:RemoveTimer(self,self.SendPingData)
    ScheduleService:AddTimer(self,self.SendPingData, 1)
end

function GameTimeService:OnPongResponse(inMsgData)
    self.time:SetServerTime(inMsgData.time)
    ScheduleService:RemoveTimer(self,self.SendPingData)
    ScheduleService:AddTimer(self,self.SendPingData, 1)
end

function GameTimeService:SendPingData()
    FrostLogD(self.__classname, "GameTimeService:SendPingData",MSG_NET_CODE.MSG_NET_CODE_CSPingReq)
    NetMessageService:Send(MSG_NET_CODE.MSG_NET_CODE_CSPingReq, {})
end

return GameTimeService