---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/9 18:25
---

local GameMainNetController = {}
GameMainConst = {
    Status = {},
    Event = {
        ServerData = 1010
    }
}

--- GameMainNetController 初始化
function GameMainNetController:Init()
    --- 初始化事件
    GameMainNetController:InitEvent()
end

--- GameMainNetController 事件初始化
function GameMainNetController:InitEvent()
    GlobalEventSystem:Bind(GameMainConst.Event.ServerData, function(response)
        GameMainNetController:AtServerConfigResponse(response)
    end)
end

function GameMainNetController:AtServerConfigResponse(response)
    ServerDataManager:GetInstance().SetItemBaseDataList(response.bagItemEntityList)
    CommonController.Instance.snackbar:OpenUIDataScenePanel(1, 1)
    DispatchEvent(LoginConfig.eventNotification.CLOSE_LOGIN_INIT_PANEL)
    DispatchEvent(GameMainConfig.eventNotification.OPEN_GAMEMAIN_PANEL)
end

return GameMainNetController