---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/7/6 10:40
---

---@class PhysicalPowerNetController
local PhysicalPowerNetController = class("physicalPowerNetController")

PhysicalConst = {
    Status = {

    },
    Event = {
        PhysicalPowerRequest = 1023,
        PhysicalPowerResponse = 1024,
    }
}

function PhysicalPowerNetController:Init( )
    self:InitEvent()
end

--- 初始化 事件
function PhysicalPowerNetController:InitEvent()
    GlobalEventSystem:Bind(PhysicalConst.Event.PhysicalPowerResponse, function(res)
        physicalPowerNetController:AtPhysicalPowerResponse(res)
    end)
end

--- 发起体力请求 刷新
function PhysicalPowerNetController:AtPhysicalPowerResponse(response)
    GameMainViewController:GetInstance():ShowPhysicalPowerPanel(response)
end

return PhysicalPowerNetController