--- 注册
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/5/24 0:16

---@class RegisterRequest
local RegisterRequest = class("RegisterRequest")
---@type RegisterRequest
local this = RegisterRequest
function RegisterRequest:ctor()
    printDebug("call lua function RegisterRequest ctor")
    self.account = string.empty
    self.password = string.empty
    self.affirmPassword = string.empty
end

function RegisterRequest:new(account, password, affirmPassword)
    self.account = account               -- java.lang.String
    self.password = password             -- java.lang.String
    self.affirmPassword = affirmPassword -- java.lang.String

    return this
end

function RegisterRequest:protocolId()
    return 1005
end

function RegisterRequest:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or RegisterRequest
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function RegisterRequest:read(buffer)
    local jsonString = buffer:readString()
    ---字节读取器中存放字符
    local data = JSON.decode(jsonString)
    return RegisterRequest:new(data.packet.account, data.packet.password, data.packet.affirmPassword)
end

return RegisterRequest
