---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/5 0:07
---

---@class MVCService:ServiceBase
local MVCService = class("MVCService", ServiceBase)

return MVCService
