---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/21 下午11:57
---
---@class UIPrefab
---@field uPrefab UnityEngine.GameObject
local UIPrefab = class("UIPrefab")

--- 初始化
function UIPrefab:ctor()
    -- 子物体或者子面板
    ---@type table<number,UIPrefab>
    self._childList = false
    ---@type UIMediator
    self._parent = false
    self._mediator = false
end

function UIPrefab:GetUIPath(index)
end

function UIPrefab:vGetUIPath()

end
---@param mediator UIMediator
---
function UIPrefab:Create(mediator, parentPrefabCls, parentTF, argument)
    local resourcePath = self:GetUIPath()
    if not resourcePath then
        PrintError(string.format("%s  UIPrefab.Create : resource path error", self.__classname))
    end
    self._uiView = AssetService:OnLoadAssetGameObject(self:GetUIPath())

end

-- 创建 子物体
function UIPrefab:CreateChildPrefabAsync(cls)

end
function UIPrefab:OnInit()
    self:vOnInit();
end
function UIPrefab:vOnInit()
end

function UIPrefab:OnStart()
    self:vOnStart()
end

function UIPrefab:vOnStart()
end

function UIPrefab:OnHide()
    self:vOnHide()
end
---创建ui
---@param mediator UIMediator 可以通过SendAction传递到信息的对应中介
---@param parentPrefabClass UIPrefab 父ui
---@param parentTf UnityEngine.Transform UE中的父控件（即创建出的控件所要挂载的地方）
---@param argument table 自定义参数，用于vInitialize时读取
---@param customID string|number 自定义索引，给父UI查找用（即父UI可以通过这个ID找到这个UI）
---@param style number ui样式索引，对应vGetPath里的资源路径
---@param layer number parentTf为空时挂载的对应层级索引
---@param asyncLoadID number 异步加载任务ID，用来获取资源
---@param bNotAddLayer boolean 为true则不直接挂载到对应层级，由自己后续控制
---@param insertFirst boolean 是否从头部插入节点
function UIPrefab:Create(mediator, parentPrefabClass, parentTf, argument, customID, style, layer, asyncLoadID, bNotAddLayer, insertFirst)
    local resourcePath = self:GetResourcePath(style)
    if not resourcePath then
        PrintError("[%s] UIPrefab.Create : resource path error",self.__classname)
    end
    
end

--------------------------------------------------------
--- private
--- 重写 在子类
--------------------------------------------------------
function UIPrefab:vOnHide()
end
--- 向下发送更新UI（只能在实例内部调用该函数，如：self:SendUpdateUI("zvlc")，与vOnUpdateUI配合使用。自己不会调vOnUpdateUI。
--- @param id string 刷新ID标识
--- @param argument table 参数
--- @param dummy boolean 不要管这个参数 在 UIMediatorClass 内管理
function UIPrefab:SendUpdateUI(id, argument, dummy)
    if string.IsNullOrEmpty(id) then
        PrintError("id", id, "错误")
        return
    end
    if not self._childList then
        PrintError("当前", self.__classname, "没有创建子物体或者子面板")
        return
    end
    for _, v in pairs(self._childList) do
        if dummy then
            self:vOnUpdateUI(id, argument)
            return
        end
        -- 递归 向子物体发送
        v:SendUpdateUI(id, argument, dummy)
    end
end
--- 向上发送操作（只能在实例内部调用该函数，如：self:SendAction("zvlc")，与vOnAction配合使用。自己不会调vOnAction。
--- @param id string 操作ID标识
--- @param argument table 参数
--- @param dummy boolean 不要管这个参数
function UIPrefab:SendAction(id, argument, dummy)
    if not self._parent then
        PrintError(self.__classname, "当前没有通知没有父组件")
        return
    end
    if self._parent then
        if dummy then
            self._parent:vOnAction(id, argument)
            return
        end
        self._parent:SendAction(id, argument, dummy)
    end
end

--- 重载
--- 更新UI回调，以 module -> mediator -> parent UI prefab -> child UI prefab 顺序向下传递（其中任何一个都可以自主发起下发传递，不必然从module开始），与SendUpdateUI配合使用
--- @param id string|number 更新标识，推荐使用字符串和数字
--- @param argument table 自定义更新参数
--- @return boolean 是否阻断向下传递刷新，true为阻断
function UIPrefab:vOnUpdateUI(id, argument)
end
--- 重载
--- 操作回调，以 child UI prefab -> parent UI prefab -> mediator -> module顺序向上传递（其中任何一个都可以自主发起下发传递，不必然从child UI prefab开始）,与SendAction配合使用
--- @param id string|number 操作标识，推荐使用字符串和数字
--- @param argument table 自定义操作参数
--- @return boolean 是否阻断向上传递操作，true为阻断
function UIPrefab:vOnAction(id, argument)

end
return UIPrefab