---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/29 下午9:37
---
---@class UIPrefabAsset:FrostGameObject
local UIPrefabAsset = class("UIPrefabAsset", FrostGameObject)
function UIPrefabAsset:ctor()
    ---@type ZJYFrameWork.UISerializable.UIView 这里获取的是 unity UI预制体的 UIView
    self.uPrefabView = false
    ---@type boolean 点击 作为显示用 改值需要 调用set 函数 不调用改值并不会改变c# 侧值
    self.IsBlocksRaycasts = false
    self.Alpha = GlobalEnum.EInvalidDefine.Alpha
    self.Interactable = false
    self.CanvasGroup = false
end

---@param inIsBlocksRaycasts boolean
function UIPrefabAsset:SetIsBlocksRaycasts(inIsBlocksRaycasts)
    self.uPrefabView.GetSelfObjCanvasGroup.IsBlocksRaycasts = inIsBlocksRaycasts
    self.IsBlocksRaycasts = inIsBlocksRaycasts
end

---@param inAlpha number 显示
function UIPrefabAsset:SetAlpha(inAlpha)
    self.uPrefabView.GetSelfObjCanvasGroup.alpha = inAlpha
    self.Alpha = inAlpha
    if not then
        
    end
end

---@param inInteractable boolean 是否可以点击
function UIPrefabAsset:SetInteractable(inInteractable)
    self.uPrefabView.GetSelfObjCanvasGroup.Interactable = inInteractable
    self.Interactable = inInteractable
end

return UIPrefabAsset