---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/21 下午11:57
---
---@class UIPrefab
local UIPrefab = class("UIPrefab")

--- 初始化
function UIPrefab:ctor()

end

function UIPrefab:

return UIPrefab