---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/5 23:12
---


--- 配置器
local ServerNetConfigConst = {
    Const = {
        
    }
}

return ServerNetConfigConst

