---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/17 12:04
---

---@class UIBaseView:LuaUIObject
UIBaseView = class("UIBaseView", LuaUIObject)

function UIBaseView:Load(viewConfig)
    self.viewConfig = viewConfig
    --- OnShow 事件
    self.showFunc = function()
        viewConfig.showFunc()
    end
    --- OnInit 事件
    self.initFunc = function()
        viewConfig.initFunc()
    end
    self.hideFunc = function()
        viewConfig.hideFunc()
    end
    self.viewPanel = viewConfig.viewPanel
    self.Config = viewConfig.Config
end

function UIBaseView:ViewPanelInit(UIView)
    self.viewPanel:Init(UIView)
end

function UIBaseView:SetReUseBool(value)
    self.reUse = value
end

function UIBaseView:ReUse()
    if self.Config.sortType == UIConfigEnum.UISortType.First then
        self.transform:SetAsFirstSibling()
    else
        --- 将变换移动到本地变换列表的末尾
        if self.Config.sortType == UIConfigEnum.UISortType.Last then
            self.transform:SetAsLastSibling()
        end
    end
    self:OnShow()
end

function UIBaseView:InstantiateGameObject(gameObject)
    local parent = self:GetPanelUIRoot(self.Config.canvasType)
    local go = CS.UnityEngine.Object.Instantiate(gameObject, parent, true) or CS.UnityEngine.GameObject
    self:SetPanel({ gameObject = go })
    local rectTransform = self:GetComponent("RectTransform")

    rectTransform.offsetMax = Vector2.zero
    rectTransform.offsetMin = Vector2.zero
    rectTransform.localScale = Vector3.one
    rectTransform.localPosition = Vector3.zero
    --- 将变换移动到本地变换列表的开头
    if self.Config.sortType == UIConfigEnum.UISortType.First then
        self.transform:SetAsFirstSibling()
    else
        --- 将变换移动到本地变换列表的末尾
        if self.Config.sortType == UIConfigEnum.UISortType.Last then
            self.transform:SetAsLastSibling()
        end
    end
    self.UIView = self:GetComponent("UIView")
    self.UIView.GetTransform.localScale = Vector3.one
    self.UIView.GetTransform.localPosition = Vector3.zero
    return go
end

function UIBaseView:GetPanelUIRoot(canvasType)
    ---UIRoot决定 UI所生成的位置
    local Root = CS.ZJYFrameWork.Config.AppConfig.GetRoot
    local switch = {
        [1] = function()
            return Root.GetBgTransformPanel
        end,
        [2] = function()
            return Root.GetUITransformPanel
        end,
        [3] = function()
            return Root.GetUITopTransformPanel
        end,
        [4] = function()
            return Root.GetNoticeCanvasTransformPanel
        end,
        [5] = function()
            return Root.GetBgTransformPanel
        end,
        [6] = function()
            return Root.GetActivieseCanvasTransformPanel
        end
    }
    local switchAction = switch[canvasType]
    if switchAction then
        return switchAction()
    end
    --- 返回空
    return nil
end

function UIBaseView:OnInit()
    self.initFunc()
end

function UIBaseView:OnShow()
    self.UIView:OnShow()
    self.showFunc()
end

function UIBaseView:OnHide()
    self.UIView:OnClose()
    self.hideFunc()
end
