---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/5 23:02
---

ServerConfigController = {}
function ServerConfigController:GetInstance()
    return ServerConfigController
end

function ServerConfigController.Init()

end

return ServerConfigController
