---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/24 14:35
---
---@class LoginTapToStartRequest
local LoginTapToStartRequest = class("LoginTapToStartRequest")
local this = LoginTapToStartRequest
function LoginTapToStartRequest:ctor()
    self.clientName = string.empty
end

function LoginTapToStartRequest:new(clientName)
    self.clientName = clientName
    return self
end

function LoginTapToStartRequest:protocolId()
    return 1013
end

function LoginTapToStartRequest:write()
    local message = {
        protocolId = self:protocolId(),
        packet = { clentName = self.clientName }
    }
    local jsonStr = JSON.encode(message)
    return jsonStr
end

function LoginTapToStartRequest:read(data)
    return LoginTapToStartRequest:new()
end

return LoginTapToStartRequest
