---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/29 下午2:55
---

---@class FrostUIText
---@field uText UnityEngine.UI.Text
local FrostUIText = class("FrostObject", FrostGameObject)

function FrostUIText:ctor()
	self._text = false
	---@type UnityEngine.UI.FontData
	self._fontData = false
	self._textCache = false
end

function FrostUIText:Init(argument)
	self.uText = argument.text
	self.__super:Init({ uGameObject = argument.text.gameObject })
end

--- public
--- 返回字体
---@return UnityEngine.Font
function FrostUIText:GetFont()
	return self._fontData.font
end

--- public
--- 设置 字体
-----@param fontData any
function FrostUIText:SetFont(fontData)
	if self._fontData.fontData == fontData then
		return
	end
	self.uText.font = fontData
	self._fontData = self.uText.font
end

return FrostUIText

