---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/29 下午2:55
---

---@class FrostUIText
---@field uText UnityEngine.UI.Text
local FrostUIText = class("FrostObject", FrostGameObject)

function FrostUIText:ctor()
    self._text = false
    self._fontData = false
    self._textCache = false
end

function FrostUIText:Init(argument)
    self.uText = argument.text
    self.super:Init({uGameObject=argument.text.gameObject})
end

return FrostUIText