--- 角色 界面
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/2 下午4:02
---

----@class CharacterUIView:UIView
local CharacterUIView = class("CharacterUIView", UIView)
function CharacterUIView:OnLoad()
    PrintDebug("init view config")
    self.UIConfig = {
        Config = UIEventConfig.LoginConfig,
        viewPanel = GameMainUIPanelView,
        initFunc = function()
            PrintDebug("CharacterUIView:Init()")
            CharacterUIView:OnInit()
        end,
        showFunc = function()
            PrintDebug("CharacterUIView:showUI()-->showFunc")
            CharacterUIView:OnShow()
        end,
        hideFunc = function()
        end,
    }
    self:Load(self.UIConfig)
    self:LoadUI(self.UIConfig)
    self:InstanceOrReuse()
end

--- 初始化
function CharacterUIView:OnInit()
end

return CharacterUIView