---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/2 下午4:32
---
---@class CharacterUIController
local CharacterUIController = class("CharacterUIController")
---@return CharacterUIController
local instance = nil

function CharacterUIController:ctor()
    -- 初始化相关

    ---@type CharacterUIView
    self.characterView = nil;
end

function CharacterUIController:GetInstance()
    if not instance then
        instance = CharacterUIController()
    end
    return instance
end

function CharacterUIController:OnInit()
    if self.characterView ~= nil then
        -- 不为空
    else
        self:OnOpen()
    end
end

function CharacterUIController:OnOpen()
    if self.characterView == nil then
        local view = require(UIEventConfig.CharacterUIConfig.prefabName)
        self.characterView = view()
        --- 读取相关
        self.characterView:OnLoad()
        return
    end
end
return CharacterUIController