---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/23 13:38
---
---@class LoginRequest
local LoginRequest = class("LoginRequest")
---@type LoginRequest
local this = LoginRequest
function LoginRequest:ctor()
    printDebug("call loginRequest function ctor")
    self.account = string.empty
    self.password = string.empty
end

---@param account string 用户名
---@param password string 密码
function LoginRequest:new(account, password)
    -- local obj = {
    self.account = account   -- java.lang.String
    self.password = password -- java.lang.String
    -- }
    -- setmetatable(obj, self)
    -- self.__index = self
    -- return obj
    return this
end

function LoginRequest:protocolId()
    return 1000
end

function LoginRequest:write(buffer, packet)
    if packet == nil then
        return
    end
    local data = packet or LoginRequest
    local message = {
        protocolId = data.protocolId(),
        packet = data
    }
    local jsonStr = JSON.encode(message)
    buffer:writeString(jsonStr)
end

function LoginRequest:read(buffer)
    local jsonString = buffer:readString()
    ---字节读取器中存放字符
    local data = JSON.decode(jsonString)
    return LoginRequest:new(data.packet.account, data.packet.password)
end

return LoginRequest
