---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/5/23 13:38
---
---@class LoginRequest
local LoginRequest = class("LoginRequest")
---@type LoginRequest
local this = LoginRequest
function LoginRequest:ctor()
    printDebug("call loginRequest function ctor")
    self.account = string.empty
    self.password = string.empty
end

---@param account string 用户名
---@param password string 密码
function LoginRequest:new(account, password)
    printDebug("account:"..account..",password:"..password)
    self.account = account   -- java.lang.String
    self.password = password -- java.lang.String
    return self
end

function LoginRequest:protocolId()
    return 1000
end

---@return string|nil
function LoginRequest:write()
    printDebug(self.account)
    printDebug(self.password)
    local message = {
        protocolId = self:protocolId(),
        packet = { account = self.account, password = self.password }
    }
    local jsonStr = JSON.encode(message)
    printDebug(jsonStr)

    return jsonStr
end

function LoginRequest:read(buffer)
    local jsonString = buffer:readString()
    ---字节读取器中存放字符
    local data = JSON.decode(jsonString)
    return LoginRequest:new(data.packet.account, data.packet.password)
end

return LoginRequest
