--- 背包 Config
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/5/15 下午9:24
---
BagUIConfig = {
    weaponIconAtlasName = "UIBagWeaponIcon_spriteatlas",
}
--- 当前 UI 交互事件 消息
BagUIConfig.eventNotification = {
    --- 打开游戏主界面
    openBagUIPanel = "openBagUIPanel",
    --- 关闭 游戏主界面
    closeBagUIPanel = "closeBagUIPanel",
}