---@class UnityEngine.RuntimePlatform : System.Enum
---@field public value__ number
---@field public OSXEditor number
---@field public OSXPlayer number
---@field public WindowsPlayer number
---@field public WindowsEditor number
---@field public IPhonePlayer number
---@field public Android number
---@field public LinuxPlayer number
---@field public LinuxEditor number
---@field public WebGLPlayer number
---@field public WSAPlayerX86 number
---@field public WSAPlayerX64 number
---@field public WSAPlayerARM number
---@field public PS4 number
---@field public XboxOne number
---@field public tvOS number
---@field public Switch number
---@field public Lumin number

---@type UnityEngine.RuntimePlatform
UnityEngine.RuntimePlatform = { }
