---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/12 23:59
---

local ZJYFrameWork=require("NameSpace.ZJYFrameWork")
local _hotfix={
    Hotfix=ZJYFrameWork.Hotfix
}
local Hotfix={
    Common=_hotfix.Hotfix.Common
}


return Hotfix