---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/7/6 11:43
---

local ZJYFrameWork=require("NameSpace.ZJYFrameWork")
local Scheduler={
    Scheduler=ZJYFrameWork.Scheduler
}
return Scheduler