---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangjingyi.
--- DateTime: 2023/6/13 15:48
---

local ZJYFrameWork = require("NameSpace.ZJYFrameWork")
local CSSpring = ZJYFrameWork.Spring
local Spring = {
    Core = CSSpring.Core,
}
return Spring